-- =============================================
-- Paths Games - Database Schema V0.10.8
-- Gaming Social Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: gaming_trades, gaming_movement_invites,
--         gaming_notification_queue, gaming_user_sessions,
--         chat_messages
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: gaming_, chat_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS gaming_trades (
    id                          INTEGER NOT NULL,
    uuid                        TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match                    INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match_sender   INTEGER NOT NULL,
    id_character_match_dest     INTEGER NOT NULL,
    id_item                     INTEGER REFERENCES list_items(id),
    id_inventory_items          INTEGER,
    status                      TEXT    NOT NULL DEFAULT 'PENDING_VALIDATION', -- PENDING_VALIDATION, ACCEPTED, REFUSED, FAILED_INVALID, EXPIRED
    timeout                     TEXT,
    resource                    TEXT,                             -- food, magic, coin
    amount                      INTEGER DEFAULT 0,
    ts_insert                   TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                   TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match),
    UNIQUE (id),
    FOREIGN KEY (id_character_match_sender, id_match) REFERENCES gaming_character_instance(id, id_match),
    FOREIGN KEY (id_character_match_dest, id_match) REFERENCES gaming_character_instance(id, id_match),
    FOREIGN KEY (id_inventory_items, id_match) REFERENCES gaming_inventory_items(id, id_match)
);

CREATE TABLE IF NOT EXISTS gaming_movement_invites (
    id                          INTEGER NOT NULL,
    uuid                        TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match                    INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match_sender   INTEGER NOT NULL,
    id_character_match_friend   INTEGER NOT NULL,
    state                       TEXT    NOT NULL DEFAULT 'PENDING', -- PENDING, ACCEPTED, EXPIRED, CANCELLED
    timestamp_send              TEXT    NOT NULL DEFAULT (datetime('now')),
    timestamp_timeout           TEXT,
    timestamp_answer            TEXT,
    energy_cost                 INTEGER DEFAULT 0,
    ts_insert                   TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                   TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match),
    UNIQUE (id),
    FOREIGN KEY (id_character_match_sender, id_match) REFERENCES gaming_character_instance(id, id_match),
    FOREIGN KEY (id_character_match_friend, id_match) REFERENCES gaming_character_instance(id, id_match)
);

CREATE TABLE IF NOT EXISTS gaming_notification_queue (
    id               INTEGER NOT NULL,
    uuid             TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match         INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_chat          INTEGER,
    flag_system_push INTEGER NOT NULL DEFAULT 0,
    timestamp        TEXT    NOT NULL DEFAULT (datetime('now')),
    type             TEXT,
    priority         INTEGER DEFAULT 0,
    ts_insert        TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update        TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match),
    UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS gaming_user_sessions (
    id        INTEGER NOT NULL,
    uuid      TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_user   INTEGER NOT NULL REFERENCES users(id),
    id_match  INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    last_seen TEXT    DEFAULT (datetime('now')),
    is_online INTEGER NOT NULL DEFAULT 0,
    client_id TEXT,
    ip        TEXT,
    device    TEXT,
    channel   TEXT,
    ts_insert TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match),
    UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match            INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_user             INTEGER NOT NULL REFERENCES users(id),
    id_character_match  INTEGER,
    message             TEXT    NOT NULL,
    timestamp           TEXT    NOT NULL DEFAULT (datetime('now')),
    counter             INTEGER DEFAULT 0,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match),
    UNIQUE (id),
    FOREIGN KEY (id_character_match, id_match) REFERENCES gaming_character_instance(id, id_match)
);
