-- =============================================
-- Paths Games - Database Schema V0.10.10
-- Snapshot Table (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: system_snapshot
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: system_)
-- =============================================
-- system_snapshot.type: FULL or LIGHT
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS system_snapshot (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid        TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story    INTEGER NOT NULL REFERENCES list_stories(id),
    id_match    INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    timestamp   TEXT    NOT NULL DEFAULT (datetime('now')),
    type        TEXT    NOT NULL DEFAULT 'FULL',
    jsonb_data  TEXT,
    file_path   TEXT,
    description TEXT,
    ts_insert   TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update   TEXT    NOT NULL DEFAULT (datetime('now'))
);
