-- =============================================
-- Paths Games - Database Schema V0.10.5
-- Story Content Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: list_creator, list_cards, list_texts
-- Reference: Step 09 - Design Core Data Model (Section 1.3)
-- Naming:   Step 06 - Naming Conventions (prefix: list_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS list_creator (
    id            INTEGER NOT NULL,
    uuid          TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story      INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text       INTEGER,                                       -- references list_texts(id_text)
    link          TEXT,
    url           TEXT,
    url_image     TEXT,
    url_emote     TEXT,
    url_instagram TEXT,
    ts_insert     TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update     TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story)
);

CREATE TABLE IF NOT EXISTS list_cards (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    url_immage          TEXT,
    id_text_title       INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    id_text_copyright   INTEGER,                                 -- references list_texts(id_text)
    link_copyright      TEXT,
    id_creator          INTEGER,
    alternative_image   TEXT,
    awesome_icon        TEXT,
    style_main          TEXT,
    style_detail        TEXT,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_creator, id_story) REFERENCES list_creator(id, id_story)
);

CREATE TABLE IF NOT EXISTS list_texts (
    id                INTEGER NOT NULL,
    uuid              TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story          INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text           INTEGER NOT NULL,
    lang              TEXT    NOT NULL DEFAULT 'en',
    short_text        TEXT,
    long_text         TEXT,
    id_text_copyright INTEGER,                                   -- references list_texts(id_text)
    link_copyright    TEXT,
    id_creator        INTEGER,
    ts_insert         TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update         TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_creator, id_story) REFERENCES list_creator(id, id_story),
    UNIQUE (id_story, id_text, lang)
);
