-- =============================================
-- Paths Games - Database Schema V0.10.7
-- Gaming State Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: gaming_state_registry, gaming_state_locations,
--         gaming_turn_queue, gaming_active_effects,
--         gaming_active_choices, gaming_story_progress,
--         gaming_temp_variables
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: gaming_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS gaming_state_registry (
    id               INTEGER NOT NULL,
    uuid             TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match         INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    key              TEXT    NOT NULL,
    string_value     TEXT,
    int_value        INTEGER,
    id_character     INTEGER,
    id_event         INTEGER REFERENCES list_events(id),
    id_choice        INTEGER REFERENCES list_choices(id),
    clock            INTEGER,
    id_mission       INTEGER REFERENCES list_missions(id),
    id_mission_steps INTEGER REFERENCES list_missions_steps(id),
    ts_insert        TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update        TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match),
    FOREIGN KEY (id_character, id_match) REFERENCES gaming_character_instance(id, id_match)
);

CREATE TABLE IF NOT EXISTS gaming_state_locations (
    id_match             INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_location          INTEGER NOT NULL REFERENCES list_locations(id),
    uuid                 TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    flag_already_actived INTEGER NOT NULL DEFAULT 0,
    clock_counter        INTEGER DEFAULT 0,
    ts_insert            TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update            TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id_match, id_location)
);

CREATE TABLE IF NOT EXISTS gaming_turn_queue (
    id_match           INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match INTEGER NOT NULL,
    uuid               TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    clock              INTEGER NOT NULL,
    timestamp_start    TEXT,
    timestamp_end      TEXT,
    pass_counter       INTEGER NOT NULL DEFAULT 0,
    priority           INTEGER NOT NULL DEFAULT 0,              -- (DES*3 + INT*2 + COS*1) * 1000 + LIFE*10 + CHARACTER_ID
    ts_insert          TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update          TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id_match, id_character_match),
    FOREIGN KEY (id_character_match, id_match) REFERENCES gaming_character_instance(id, id_match) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gaming_active_effects (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match            INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  INTEGER NOT NULL,
    clock               INTEGER,
    id_choise           INTEGER REFERENCES list_choices(id),
    timestamp_start     TEXT    NOT NULL DEFAULT (datetime('now')),
    timestamp_timeout   TEXT,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match),
    FOREIGN KEY (id_character_match, id_match) REFERENCES gaming_character_instance(id, id_match) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gaming_active_choices (
    id        INTEGER NOT NULL,
    uuid      TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match  INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    clock     INTEGER,
    id_event  INTEGER REFERENCES list_events(id),
    id_choise INTEGER REFERENCES list_choices(id),
    ts_insert TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match)
);

CREATE TABLE IF NOT EXISTS gaming_story_progress (
    id        INTEGER NOT NULL,
    uuid      TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match  INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    clock     INTEGER,
    id_event  INTEGER REFERENCES list_events(id),
    id_choise INTEGER REFERENCES list_choices(id),
    ts_insert TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match)
);

CREATE TABLE IF NOT EXISTS gaming_temp_variables (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match            INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  INTEGER,
    key                 TEXT    NOT NULL,
    value               TEXT,
    type                TEXT,                                     -- CLOCK, EVENT, LOCATION, RESOURCES, TRAITS, etc.
    timestamp           TEXT    DEFAULT (datetime('now')),
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_match),
    FOREIGN KEY (id_character_match, id_match) REFERENCES gaming_character_instance(id, id_match) ON DELETE CASCADE
);
