-- =============================================
-- Paths Games - Database Schema V0.10.3
-- Story Locations & Items Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: list_locations, list_locations_neighbors, list_items,
--         list_items_effects, list_weather_rules
-- Reference: Step 09 - Design Core Data Model (Section 1.3)
-- Naming:   Step 06 - Naming Conventions (prefix: list_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS list_locations (
    id                                     INTEGER NOT NULL,
    uuid                                   TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card                                INTEGER,             -- logical FK to list_cards(id)
    id_story                               INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_name                           INTEGER,             -- references list_texts(id_text)
    id_text_description                    INTEGER,             -- references list_texts(id_text)
    id_text_narrative                      INTEGER,             -- references list_texts(id_text)
    id_image                               INTEGER,
    is_safe                                INTEGER NOT NULL DEFAULT 0,
    cost_energy_enter                      INTEGER NOT NULL DEFAULT 1,
    counter_time                           INTEGER,
    id_event_if_counter_zero               INTEGER,             -- logical FK to list_events(id)
    secure_param                           INTEGER DEFAULT 0,
    id_event_if_character_start_time       INTEGER,             -- logical FK to list_events(id)
    id_event_if_character_enter_first_time INTEGER,             -- logical FK to list_events(id)
    id_event_if_first_time                 INTEGER,             -- logical FK to list_events(id)
    id_event_not_first_time                INTEGER,             -- logical FK to list_events(id)
    priority_automatic_event               INTEGER DEFAULT 0,
    id_audio                               INTEGER,
    max_characters                         INTEGER DEFAULT 100,
    ts_insert                              TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                              TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story)
);

CREATE TABLE IF NOT EXISTS list_locations_neighbors (
    id                       INTEGER NOT NULL,
    uuid                     TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story                 INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_location_from         INTEGER NOT NULL,
    id_location_to           INTEGER NOT NULL,
    direction                TEXT    NOT NULL,                    -- NORTH, SOUTH, EAST, WEST, ABOVE, BELOW, SKY
    flag_back                INTEGER NOT NULL DEFAULT 0,
    condition_registry_key   TEXT,
    condition_registry_value TEXT,
    energy_cost              INTEGER DEFAULT 0,
    id_text_go               INTEGER,                            -- references list_texts(id_text)
    id_text_back             INTEGER,                            -- references list_texts(id_text)
    ts_insert                TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_location_from, id_story) REFERENCES list_locations(id, id_story) ON DELETE CASCADE,
    FOREIGN KEY (id_location_to, id_story) REFERENCES list_locations(id, id_story) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS list_items (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card             INTEGER,                                 -- logical FK to list_cards(id)
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_name        INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    weight              INTEGER NOT NULL DEFAULT 1,
    is_consumabile      INTEGER NOT NULL DEFAULT 1,
    id_class_permitted  INTEGER,
    id_class_prohibited INTEGER,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_class_permitted, id_story) REFERENCES list_classes(id, id_story),
    FOREIGN KEY (id_class_prohibited, id_story) REFERENCES list_classes(id, id_story)
);

CREATE TABLE IF NOT EXISTS list_items_effects (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_item             INTEGER NOT NULL,
    id_text_name        INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    effect_code         TEXT    NOT NULL,                         -- LIFE, ENERGY, SADNESS, DEX, INT, COS, FOOD, MAGIC, COIN
    effect_value        INTEGER NOT NULL DEFAULT 0,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_item, id_story) REFERENCES list_items(id, id_story) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS list_weather_rules (
    id                          INTEGER NOT NULL,
    uuid                        TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card                     INTEGER,                         -- logical FK to list_cards(id)
    id_story                    INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_name                INTEGER,                         -- references list_texts(id_text)
    id_text_description         INTEGER,                         -- references list_texts(id_text)
    probability                 INTEGER NOT NULL DEFAULT 0,
    cost_move_safe_location     INTEGER DEFAULT 0,
    cost_move_not_safe_location INTEGER DEFAULT 0,
    condition_key               TEXT,
    condition_key_value         TEXT,
    time_from                   INTEGER,
    time_to                     INTEGER,
    id_text                     INTEGER,                         -- references list_texts(id_text)
    active                      INTEGER NOT NULL DEFAULT 1,
    priority                    INTEGER DEFAULT 0,
    delta_energy                INTEGER DEFAULT 0,
    id_event                    INTEGER,                         -- logical FK to list_events(id)
    ts_insert                   TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                   TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story)
);
