-- =============================================
-- Paths Games - Database Schema V0.10.2
-- Story Core Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: list_stories, list_stories_difficulty, list_keys,
--         list_classes, list_classes_bonus, list_traits,
--         list_character_templates
-- Reference: Step 09 - Design Core Data Model (Section 1.3)
-- Naming:   Step 06 - Naming Conventions (prefix: list_)
-- =============================================
-- Note: list_stories has forward-reference columns to tables created
--       in later migrations (list_cards, list_locations, list_events,
--       list_creator). SQLite does not support ALTER TABLE ADD CONSTRAINT,
--       so these FKs are documented but not enforced at DB level.
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS list_stories (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                        TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card                     INTEGER,                         -- logical FK to list_cards(id)
    id_text_title               INTEGER,                         -- references list_texts(id_text)
    id_text_description         INTEGER,                         -- references list_texts(id_text)
    author                      TEXT,
    version_min                 TEXT,
    version_max                 TEXT,
    id_location_start           INTEGER,                         -- logical FK to list_locations(id)
    id_image                    INTEGER,
    id_location_all_player_coma INTEGER,                         -- logical FK to list_locations(id)
    id_event_all_player_coma    INTEGER,                         -- logical FK to list_events(id)
    id_text_clock_singular      INTEGER DEFAULT 10,
    id_text_clock_plural        INTEGER DEFAULT 11,
    id_event_end_game           INTEGER,                         -- logical FK to list_events(id)
    id_text_copyright           INTEGER,                         -- references list_texts(id_text)
    link_copyright              TEXT,
    id_creator                  INTEGER,                         -- logical FK to list_creator(id)
    category                    TEXT,
    "group"                     TEXT,
    visibility                  TEXT    DEFAULT 'PUBLIC',
    priority                    INTEGER DEFAULT 0,
    peghi                       INTEGER DEFAULT 0,
    ts_insert                   TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                   TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS list_stories_difficulty (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                     TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card                  INTEGER,                            -- logical FK to list_cards(id)
    id_story                 INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_description      INTEGER,                            -- references list_texts(id_text)
    exp_cost                 INTEGER NOT NULL DEFAULT 5,
    max_weight               INTEGER NOT NULL DEFAULT 10,
    min_character            INTEGER NOT NULL DEFAULT 1,
    max_character            INTEGER NOT NULL DEFAULT 4,
    cost_help_coma           INTEGER NOT NULL DEFAULT 3,
    cost_max_characteristics INTEGER NOT NULL DEFAULT 3,
    number_max_free_action   INTEGER NOT NULL DEFAULT 1,
    ts_insert                TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                TEXT    NOT NULL DEFAULT (datetime('now')),
    UNIQUE (id, id_story)
);

CREATE TABLE IF NOT EXISTS list_keys (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card             INTEGER,                                 -- logical FK to list_cards(id)
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    name                TEXT    NOT NULL,
    value               TEXT,
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    "group"             TEXT,
    priority            INTEGER DEFAULT 0,
    visibility          TEXT    DEFAULT 'PUBLIC',
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story)
);

CREATE TABLE IF NOT EXISTS list_classes (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card             INTEGER,                                 -- logical FK to list_cards(id)
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_name        INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    weight_max          INTEGER NOT NULL DEFAULT 10,
    dexterity_base      INTEGER NOT NULL DEFAULT 1,
    intelligence_base   INTEGER NOT NULL DEFAULT 1,
    constitution_base   INTEGER NOT NULL DEFAULT 1,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story)
);

CREATE TABLE IF NOT EXISTS list_classes_bonus (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card             INTEGER,                                 -- logical FK to list_cards(id)
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_class            INTEGER NOT NULL,
    statistic           TEXT    NOT NULL,                         -- energy, life, sad, dex, int, cos, food, magic, coin
    value               INTEGER NOT NULL DEFAULT 0,
    id_text_name        INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_class, id_story) REFERENCES list_classes(id, id_story) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS list_traits (
    id                  INTEGER NOT NULL,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card             INTEGER,                                 -- logical FK to list_cards(id)
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_class_permitted  INTEGER,
    id_class_prohibited INTEGER,
    id_text_name        INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    cost_positive       INTEGER DEFAULT 0,
    cost_negative       INTEGER DEFAULT 0,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_class_permitted, id_story) REFERENCES list_classes(id, id_story),
    FOREIGN KEY (id_class_prohibited, id_story) REFERENCES list_classes(id, id_story)
);

CREATE TABLE IF NOT EXISTS list_character_templates (
    id_tipo             INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card             INTEGER,                                 -- logical FK to list_cards(id)
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_name        INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    life_max            INTEGER NOT NULL DEFAULT 10,
    energy_max          INTEGER NOT NULL DEFAULT 10,
    sad_max             INTEGER NOT NULL DEFAULT 10,
    dexterity_start     INTEGER NOT NULL DEFAULT 1,
    intelligence_start  INTEGER NOT NULL DEFAULT 1,
    constitution_start  INTEGER NOT NULL DEFAULT 1,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now')),
    UNIQUE (id_tipo, id_story)
);
