-- =============================================
-- Paths Games - Repeatable Migration
-- Development & Test Seed Data (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- This file is re-executed whenever its content changes.
-- It inserts test data for development and testing purposes.
-- NEVER include this in production deployments.
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

-- Clean previous test data
DELETE FROM chat_messages       WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_choices_executed WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_lock_history    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_clock_history   WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_weather         WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_item_usage      WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_movements       WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_events          WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM system_snapshot     WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_temp_variables    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_story_progress    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_active_choices    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_active_effects    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_turn_queue        WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_state_locations   WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_state_registry    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_notification_queue WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_user_sessions     WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_movement_invites  WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_trades            WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_inventory_items   WHERE id_character_match IN (SELECT id FROM gaming_character_instance WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000));
DELETE FROM gaming_backpack_resources WHERE id_character_match IN (SELECT id FROM gaming_character_instance WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000));
DELETE FROM gaming_character_traits  WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_character_instance WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_match             WHERE id < 1000;
DELETE FROM users_tokens WHERE id_user IN (SELECT id FROM users WHERE username LIKE 'test_%');
DELETE FROM users WHERE username LIKE 'test_%';

-- =============================================
-- Test Users
-- =============================================
-- Password hash is BCrypt of 'password123'
INSERT INTO users (id, username, password_hash, email_address, role, state, nickname, language)
VALUES (1, 'test_admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'admin@test.local', 'ADMIN', 2, 'TestAdmin', 'en');

INSERT INTO users (id, username, password_hash, email_address, role, state, nickname, language)
VALUES (2, 'test_player1', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'player1@test.local', 'PLAYER', 2, 'Alice', 'en');

INSERT INTO users (id, username, password_hash, email_address, role, state, nickname, language)
VALUES (3, 'test_player2', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'player2@test.local', 'PLAYER', 2, 'Bob', 'en');

INSERT INTO users (id, username, password_hash, email_address, role, state, nickname, language)
VALUES (4, 'test_player3', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'player3@test.local', 'PLAYER', 2, 'Charlie', 'it');

-- Reset sequence after explicit ID inserts
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

-- =============================================
-- Story Seed Data: DEMO_1 and DEMO_2
-- =============================================
-- Clean previous story test data (id >= 9000)
DELETE FROM list_choices_effects       WHERE id_story IN (9001, 9002);
DELETE FROM list_choices_conditions    WHERE id_story IN (9001, 9002);
DELETE FROM list_choices               WHERE id_story IN (9001, 9002);
DELETE FROM list_events_effects        WHERE id_story IN (9001, 9002);
DELETE FROM list_events                WHERE id_story IN (9001, 9002);
DELETE FROM list_items_effects         WHERE id_story IN (9001, 9002);
DELETE FROM list_items                 WHERE id_story IN (9001, 9002);
DELETE FROM list_locations_neighbors   WHERE id_story IN (9001, 9002);
DELETE FROM list_locations             WHERE id_story IN (9001, 9002);
DELETE FROM list_weather_rules         WHERE id_story IN (9001, 9002);
DELETE FROM list_missions_steps        WHERE id_story IN (9001, 9002);
DELETE FROM list_missions              WHERE id_story IN (9001, 9002);
DELETE FROM list_global_random_events  WHERE id_story IN (9001, 9002);
DELETE FROM list_character_templates   WHERE id_story IN (9001, 9002);
DELETE FROM list_traits                WHERE id_story IN (9001, 9002);
DELETE FROM list_classes_bonus         WHERE id_story IN (9001, 9002);
DELETE FROM list_classes               WHERE id_story IN (9001, 9002);
DELETE FROM list_stories_difficulty    WHERE id_story IN (9001, 9002);
DELETE FROM list_cards                 WHERE id_story IN (9001, 9002);
DELETE FROM list_creator               WHERE id_story IN (9001, 9002);
DELETE FROM list_keys                  WHERE id_story IN (9001, 9002);
DELETE FROM list_texts                 WHERE id_story IN (9001, 9002);
DELETE FROM list_stories               WHERE id IN (9001, 9002);

-- ── Story 1: DEMO — Learn to Play (id=9001) ─────────────────────
INSERT INTO list_stories (id, uuid, author, version_min, id_text_clock_singular, id_text_clock_plural,
    category, "group", visibility, priority, peghi, id_text_title, id_text_description)
VALUES (9001, 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', 'PathsMaster', '0.14.0', 10, 11,
    'tutorial', 'tutorial', 'PUBLIC', 100, 0, 1, 2);


-- ── Story 2: Il Valvassore di Marca (id=9002) ────────────────────
INSERT INTO list_stories (id, uuid, author, version_min, id_text_clock_singular, id_text_clock_plural,
    category, "group", visibility, priority, peghi, id_text_title, id_text_description )
VALUES (9002, 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', 'PathsMaster', '0.14.0', 10, 11,
    'fantasy', 'main', 'PUBLIC', 10, 5, 1, 2 );


-- ── Story 1 Texts ───────────────────────────────────────────────
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90001, 9001, 1, 'en', 'TUTORIAL', 'Welcome to Paths Games! This guided tutorial will teach you every mechanic step by step.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90002, 9001, 1, 'it', 'TUTORIAL', 'Benvenuto in Paths Games! Questo tutorial guidato ti insegnerà ogni meccanica passo dopo passo.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90003, 9001, 2, 'en', 'A short training adventure in the Academy of Paths.', 'A short training adventure in the Academy of Paths. Learn movement, energy, items, choices, and missions in a safe environment.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90004, 9001, 2, 'it', 'Una breve avventura di addestramento.', 'Una breve avventura di addestramento nell''Accademia di Paths. Impara movimento, energia, oggetti, scelte e missioni in un ambiente sicuro.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90005, 9001, 100, 'en', 'Welcome Hall', 'A bright, welcoming hall with banners explaining the basics of Paths Games.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90006, 9001, 100, 'it', 'Sala di Benvenuto', 'Una sala luminosa e accogliente con stendardi.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90007, 9001, 101, 'en', 'Movement Training Room', 'A long corridor with colored tiles on the floor.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90008, 9001, 101, 'it', 'Sala Addestramento Movimento', 'Un lungo corridoio con mattonelle colorate.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90009, 9001, 102, 'en', 'Energy & Life Classroom', 'A cozy classroom with diagrams on a blackboard.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90010, 9001, 102, 'it', 'Aula Energia & Vita', 'Un''aula accogliente con diagrammi alla lavagna.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90011, 9001, 103, 'en', 'Item Workshop', 'A workshop filled with glowing potions and rusty swords.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90012, 9001, 103, 'it', 'Laboratorio Oggetti', 'Un laboratorio pieno di pozioni e spade.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90013, 9001, 104, 'en', 'Choice Arena', 'A circular arena with two doors: one gold, one red.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90014, 9001, 104, 'it', 'Arena delle Scelte', 'Un''arena circolare con due porte.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90015, 9001, 105, 'en', 'Weather Observatory', 'A tower with a glass dome revealing the sky.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90016, 9001, 105, 'it', 'Osservatorio Meteo', 'Una torre con una cupola di vetro.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90017, 9001, 106, 'en', 'Mission Board', 'A large board covered with quest notices.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90018, 9001, 106, 'it', 'Bacheca Missioni', 'Una grande bacheca coperta di avvisi di missioni.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90019, 9001, 107, 'en', 'Multiplayer Courtyard', 'An open courtyard where training dummies represent other players.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90020, 9001, 107, 'it', 'Cortile Multigiocatore', 'Un cortile aperto con manichini da allenamento.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91214, 9001, 109, 'en', 'Records Vault', 'A cold room of ledgers and letters.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91215, 9001, 109, 'it', 'Sala degli Archivi', 'Una stanza fredda di registri e lettere.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90021, 9001, 108, 'en', 'Graduation Hall', 'A grand hall with a golden trophy at the center.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90022, 9001, 108, 'it', 'Sala della Laurea', 'Una sala maestosa con un trofeo dorato al centro.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90029, 9001, 200, 'en', 'Student', 'A balanced beginner. Good at everything, master of nothing.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90030, 9001, 200, 'it', 'Studente', 'Un principiante equilibrato.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90031, 9001, 201, 'en', 'Scholar', 'High intelligence, low constitution.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90032, 9001, 201, 'it', 'Erudito', 'Alta intelligenza, bassa costituzione.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90033, 9001, 202, 'en', 'Athlete', 'High dexterity and constitution, lower intelligence.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90034, 9001, 202, 'it', 'Atleta', 'Alta destrezza e costituzione.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90035, 9001, 300, 'en', 'Tutorial', 'The only difficulty available for the tutorial.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90036, 9001, 300, 'it', 'Tutorial', 'L''unica difficoltà disponibile per il tutorial.');
-- v0.28.7 — weather card titles (cards 90010..90012 reference id_text 800..802).
-- Without these the weather card resolves with a null title (match logs, weather API).
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90200, 9001, 800, 'en', 'Clear Sky', 'The sun shines over the Academy.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90201, 9001, 800, 'it', 'Cielo Sereno', 'Il sole splende sull''Accademia.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90202, 9001, 801, 'en', 'Rain', 'A steady rain makes every step heavier.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90203, 9001, 801, 'it', 'Pioggia', 'Una pioggia costante rende ogni passo più pesante.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90204, 9001, 802, 'en', 'Storm', 'Thunder rolls; moving is exhausting.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90205, 9001, 802, 'it', 'Tempesta', 'Rimbomba il tuono; muoversi è sfiancante.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90071, 9001, 700, 'en', 'Quick Learner', 'You absorb knowledge faster.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90072, 9001, 700, 'it', 'Apprendista Veloce', 'Assorbi conoscenza più rapidamente.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90073, 9001, 701, 'en', 'Curious Mind', 'Your curiosity leads you to discover hidden details.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90074, 9001, 701, 'it', 'Mente Curiosa', 'La tua curiosità ti porta a scoprire dettagli nascosti.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90075, 9001, 702, 'en', 'Resilient Spirit', 'You recover quickly from setbacks.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90076, 9001, 702, 'it', 'Spirito Resiliente', 'Ti riprendi rapidamente dalle avversità.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90096, 9001, 210, 'en', 'The Student', 'A well-rounded student with equal stats.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90097, 9001, 211, 'en', 'The Bookworm', 'A studious character with high intelligence.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90098, 9001, 212, 'en', 'The Gym Star', 'An athletic character with high dexterity.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90102, 9001, 10, 'en', 'turn', 'turn');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90103, 9001, 11, 'en', 'turns', 'turns');
-- Step 23: negative-cost trait texts
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90104, 9001, 703, 'en', 'Frail Body', 'A fragile constitution lowers your maximum life.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90105, 9001, 703, 'it', 'Corpo Fragile', 'Una costituzione fragile riduce la vita massima.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90106, 9001, 704, 'en', 'Weary Soul', 'Chronic tiredness lowers your maximum energy.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90107, 9001, 704, 'it', 'Anima Stanca', 'Una stanchezza cronica riduce la energia massima.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90108, 9001, 705, 'en', 'Scroll-Touched', 'The scroll left something behind. You did not choose this, and you could not have.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90109, 9001, 705, 'it', 'Segnato dalla Pergamena', 'La pergamena ha lasciato qualcosa. Non lo hai scelto, e non avresti potuto.');

-- ── Story 1 Difficulties ────────────────────────────────────────
-- Step 23: difficulty 90001 caps trait costs (positive 2 / negative 3)
INSERT INTO list_stories_difficulty (id, id_story, id_text_description, exp_cost, max_weight, min_character, max_character, cost_help_coma, cost_max_characteristics, number_max_free_action, life, energy, sad, dexterity, intelligence, constitution, weight, trait_cost_positive_budget, trait_cost_negative_budget) VALUES (90001, 9001, 300, 1, 20, 1, 4, 1, 1, 3, 120, 110, 0, 12, 12, 12, 12, 2, 3);

-- ── Story 1 Classes ─────────────────────────────────────────────
INSERT INTO list_classes (id, id_story, id_text_name, id_text_description, weight_max, dexterity_base, intelligence_base, constitution_base) VALUES (90001, 9001, 200, 200, 12, 3, 3, 3);
INSERT INTO list_classes (id, id_story, id_text_name, id_text_description, weight_max, dexterity_base, intelligence_base, constitution_base) VALUES (90002, 9001, 201, 201, 8, 2, 5, 2);
INSERT INTO list_classes (id, id_story, id_text_name, id_text_description, weight_max, dexterity_base, intelligence_base, constitution_base) VALUES (90003, 9001, 202, 202, 10, 5, 2, 4);

-- ── Story 1 Classes Bonus ───────────────────────────────────────
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90001, 9001, 90001, 'life', 3);
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90002, 9001, 90001, 'energy', 3);
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90003, 9001, 90001, 'exp', 2);
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90004, 9001, 90002, 'int', 3);
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90005, 9001, 90002, 'energy', 2);
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90006, 9001, 90002, 'exp', 3);
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90007, 9001, 90003, 'dex', 3);
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90008, 9001, 90003, 'life', 2);
INSERT INTO list_classes_bonus (id, id_story, id_class, statistic, value) VALUES (90009, 9001, 90003, 'energy', 4);

-- ── Story 1 Traits ──────────────────────────────────────────────
-- Step 23: 90002 permitted only for class 90002, 90003 prohibited for class 90001,
-- 90004/90005 are negative-cost traits; 90001 stays unrestricted (robot loadout default)
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight, hide_on_start_match, id_class_permitted, id_class_prohibited) VALUES (90001, 9001, 700, 700, 1, 0,  2, 0, 0, 0, 0, 1, 0, 0, NULL, NULL);
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight, hide_on_start_match, id_class_permitted, id_class_prohibited) VALUES (90002, 9001, 701, 701, 1, 0,  0, 2, 0, 1, 0, 0, 0, 0, 90002, NULL);
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight, hide_on_start_match, id_class_permitted, id_class_prohibited) VALUES (90003, 9001, 702, 702, 1, 0,  0, 0, 0, 0, 2, 0, 1, 0, NULL, 90001);
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight, hide_on_start_match, id_class_permitted, id_class_prohibited) VALUES (90004, 9001, 703, 703, 0, 2, -2, 0, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight, hide_on_start_match, id_class_permitted, id_class_prohibited) VALUES (90005, 9001, 704, 704, 0, 2,  0,-2, 0, 0, 0, 0, 0, NULL, NULL, NULL);
-- v0.35.2: the one trait nobody may choose. The Guide Scroll grants it when used
-- (list_items_effects 90002), and only then does it show in the player's trait list.
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight, hide_on_start_match, id_class_permitted, id_class_prohibited) VALUES (90006, 9001, 705, 705, 0, 0,  0, 0, 0, 0, 1, 0, 0, 1, NULL, NULL);

-- ── Story 1 Character Templates ─────────────────────────────────
INSERT INTO list_character_templates (id_tipo, id_story, id_text_name, id_text_description, life_max, energy_max, sad_max, dexterity_start, intelligence_start, constitution_start, id_class_permitted, id_class_prohibited) VALUES (90001, 9001, 210, 210, 12, 12, 8, 3, 3, 3, NULL,  NULL);
INSERT INTO list_character_templates (id_tipo, id_story, id_text_name, id_text_description, life_max, energy_max, sad_max, dexterity_start, intelligence_start, constitution_start, id_class_permitted, id_class_prohibited) VALUES (90002, 9001, 211, 211, 10, 10, 6, 2, 5, 2, 90002, NULL);
INSERT INTO list_character_templates (id_tipo, id_story, id_text_name, id_text_description, life_max, energy_max, sad_max, dexterity_start, intelligence_start, constitution_start, id_class_permitted, id_class_prohibited) VALUES (90003, 9001, 212, 212, 11, 14, 7, 5, 2, 4, NULL,  90001);

-- ── Story 1 Keys ────────────────────────────────────────────────
INSERT INTO list_keys (id, id_story, name, value, "group", visibility, multi_value) VALUES (90001, 9001, 'tutorial_progress', '0', 'tutorial', 'PUBLIC', 0);
INSERT INTO list_keys (id, id_story, name, value, "group", visibility, multi_value) VALUES (90002, 9001, 'items_collected', '0', 'tutorial', 'PUBLIC', 0);
INSERT INTO list_keys (id, id_story, name, value, "group", visibility, multi_value) VALUES (90003, 9001, 'choice_made', '0', 'tutorial', 'PUBLIC', 0);
-- Step 36.1: multi_value = 1 makes a key hold a SET — each write adds a member instead of
-- replacing the value. 'evidence_found' has no default, so its set starts EMPTY: no row.
INSERT INTO list_keys (id, id_story, name, value, "group", visibility, multi_value) VALUES (90004, 9001, 'evidence_found', NULL, 'evidence', 'PUBLIC', 1);
-- Step 36.2: the case/padding test-bed. 'case_notes' is written with padding and capitals
-- while every condition on it is authored lowercase and bare; 'signal' is the mirror, its
-- lowercase default read by a padded, upper-case condition. 'vault_seen' is written by no
-- event and no choice at all: only a LOCATION writes it, by being entered.
INSERT INTO list_keys (id, id_story, name, value, "group", visibility, multi_value) VALUES (90005, 9001, 'case_notes', NULL, 'evidence', 'PUBLIC', 1);
INSERT INTO list_keys (id, id_story, name, value, "group", visibility, multi_value) VALUES (90006, 9001, 'signal', 'green', 'evidence', 'PUBLIC', 0);
INSERT INTO list_keys (id, id_story, name, value, "group", visibility, multi_value) VALUES (90007, 9001, 'vault_seen', NULL, 'evidence', 'PUBLIC', 0);

-- ── Story 1 Cards ───────────────────────────────────────────────
-- Inserted before locations: fk_locations_card (id_card, id_story) requires the card to exist.
INSERT INTO list_cards (id, id_story, url_immage, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (90001, 9001, 'https://paths.games/assets/cards/tutorial-academy.jpg', 'fas fa-graduation-cap', 'tutorial', 1, 2, 1);
-- v0.28.7: these two cards back locations 90002..90006; they need a title so the
-- location card resolves with one (match logs, locations API, admin console).
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (90002, 9001, 'fas fa-book-open', 'learning', 101, 101, 101);
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (90003, 9001, 'fas fa-lightbulb', 'tips', 102, 102, 102);
-- Step 27 — weather cards (referenced by list_weather_rules.id_card)
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (90010, 9001, 'fas fa-sun', 'weather', 800, 800, 800);
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (90011, 9001, 'fas fa-cloud-rain', 'weather', 801, 801, 801);
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (90012, 9001, 'fas fa-cloud-bolt', 'weather', 802, 802, 802);

-- ── Story 1 Locations ───────────────────────────────────────────
-- Step 26: secure_param > 0 marks a SAFE location (energy/life recovery + sadness
-- relief at time-start); the start hall (90001) is safe and carries a counter_time
-- so the location-counter decrement path is exercised where the player stands.
-- The Choice Arena (90005) is UNSAFE (secure_param 0).
-- Step 27.x: id_card on each location so locationsActive returns idCard + card.
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters, secure_param, counter_time) VALUES (90001, 9001, 90001, 100, 100, 1, 10, 1, 2);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters, secure_param) VALUES (90002, 9001, 90002, 101, 101, 1, 10, 1);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters, secure_param) VALUES (90003, 9001, 90003, 102, 102, 1, 10, 1);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters, secure_param) VALUES (90004, 9001, 90002, 103, 103, 1, 10, 1);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters, secure_param) VALUES (90005, 9001, 90003, 104, 104, 1, 10, 0);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (90006, 9001, 90003, 105, 105, 1, 10);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (90007, 9001, 90002, 106, 106, 1, 10);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (90008, 9001, 90001, 107, 107, 1, 10);
-- Step 36.2 — the Records Vault writes the registry by being entered. Two pairs: the first
-- arrival and every later one take different branches, never both, and no event is involved.
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters, key_to_add, key_value_to_add, key_to_add_not_first, key_value_to_add_not_first) VALUES (90009, 9001, 90001, 109, 109, 1, 10, 'vault_seen', 'first', 'vault_seen', 'again');

-- ── Story 1 Location Neighbors ──────────────────────────────────
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90001, 9001, 90001, 90002, 'NORTH', 1, 2);
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90002, 9001, 90002, 90003, 'EAST', 1, 0);
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90003, 9001, 90003, 90004, 'NORTH', 1, 0);
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90004, 9001, 90004, 90005, 'EAST', 1, 0);
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90005, 9001, 90005, 90006, 'NORTH', 1, 1);
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90006, 9001, 90006, 90007, 'EAST', 1, 0);
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90007, 9001, 90007, 90008, 'NORTH', 1, 0);
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90008, 9001, 90001, 90008, 'EAST', 1, 1);
INSERT INTO list_locations_neighbors (id, id_story, id_location_from, id_location_to, direction, flag_back, energy_cost) VALUES (90009, 9001, 90001, 90009, 'SOUTH', 1, 0);
-- Step 0.28.2 — optional return card on the Welcome↔Movement edge (catalog card 90003).
UPDATE list_locations_neighbors SET id_card_back = 90003 WHERE id = 90001 AND id_story = 9001;

-- ── Story 1 Items ───────────────────────────────────────────────
-- v0.34.0: every item carries a card (the board renders the object, never an id), and the
-- two class columns are finally exercised — 90005 can be used only by class 90002.
-- is_consumabile is spelled out: it used to be left to the column default, so EVERY item
-- read as consumable and the carried-only rule had nothing to bite on.
INSERT INTO list_items (id, id_story, id_card, id_text_name, id_text_description, weight, is_consumabile, flag_show_effects, max_per_character, amount_drop, amount_use, id_class_permitted, id_class_prohibited) VALUES (90001, 9001, 90001, 400, 400, 1, 1, 1,    NULL, NULL, NULL, NULL,  NULL);   -- Training Potion: consumable, LIFE +3
INSERT INTO list_items (id, id_story, id_card, id_text_name, id_text_description, weight, is_consumabile, flag_show_effects, max_per_character, amount_drop, amount_use, id_class_permitted, id_class_prohibited) VALUES (90002, 9001, 90001, 401, 401, 2, 0, 1,    NULL, NULL, NULL, NULL,  NULL);   -- Practice Sword: CARRIED ONLY, gates event 90015
INSERT INTO list_items (id, id_story, id_card, id_text_name, id_text_description, weight, is_consumabile, flag_show_effects, max_per_character, amount_drop, amount_use, id_class_permitted, id_class_prohibited) VALUES (90003, 9001, 90001, 402, 402, 1, 1, NULL, NULL, 2,    NULL, NULL,  NULL);   -- a drop puts down TWO   -- Guide Scroll: consumable, EXP +5 (flag unset = shown)
INSERT INTO list_items (id, id_story, id_card, id_text_name, id_text_description, weight, is_consumabile, flag_show_effects, max_per_character, amount_drop, amount_use, id_class_permitted, id_class_prohibited) VALUES (90004, 9001, 90001, 403, 403, 1, 1, 1,    NULL, NULL, NULL, NULL,  NULL);   -- Energy Snack: consumable, ENERGY +3
INSERT INTO list_items (id, id_story, id_card, id_text_name, id_text_description, weight, is_consumabile, flag_show_effects, max_per_character, amount_drop, amount_use, id_class_permitted, id_class_prohibited) VALUES (90005, 9001, 90001, 404, 404, 1, 1, 1,    1,    NULL, NULL, 90002, NULL);   -- and only ONE ever   -- Scholar's Tonic: only class 90002 may use it
INSERT INTO list_items (id, id_story, id_card, id_text_name, id_text_description, weight, is_consumabile, flag_show_effects, max_per_character, amount_drop, amount_use, id_class_permitted, id_class_prohibited) VALUES (90006, 9001, 90001, 405, 405, 9, 1, 0,    NULL, NULL, NULL, NULL,  NULL);   -- Lead Ingot: heavy, and its effect stays SECRET

-- ── Story 1 Item Effects ────────────────────────────────────────
-- v0.34.0 adds traits_to_add / traits_to_remove: same CSV-of-ids format as the event
-- effects. SADNESS is the documented alias of the `sad` statistic.
INSERT INTO list_items_effects (id, id_story, id_card, id_item, effect_code, effect_value, traits_to_add, traits_to_remove) VALUES (90001, 9001, 90001, 90001, 'LIFE', 3, NULL, NULL);
INSERT INTO list_items_effects (id, id_story, id_card, id_item, effect_code, effect_value, traits_to_add, traits_to_remove) VALUES (90002, 9001, 90001, 90003, 'EXP', 5, '90006', NULL);   -- v0.35.2: grants the HIDDEN trait
INSERT INTO list_items_effects (id, id_story, id_card, id_item, effect_code, effect_value, traits_to_add, traits_to_remove) VALUES (90003, 9001, 90001, 90004, 'ENERGY', 3, NULL, NULL);
INSERT INTO list_items_effects (id, id_story, id_card, id_item, effect_code, effect_value, traits_to_add, traits_to_remove) VALUES (90004, 9001, 90001, 90005, 'SADNESS', 1, NULL, NULL);
INSERT INTO list_items_effects (id, id_story, id_card, id_item, effect_code, effect_value, traits_to_add, traits_to_remove) VALUES (90005, 9001, 90001, 90006, 'LIFE', 1, NULL, NULL);

-- ── Story 1 Weather Rules ───────────────────────────────────────
INSERT INTO list_weather_rules (id, id_story, id_card, id_text_name, probability, active) VALUES (90001, 9001, 90010, 800, 50, 1);
INSERT INTO list_weather_rules (id, id_story, id_card, id_text_name, probability, active) VALUES (90002, 9001, 90011, 801, 35, 1);
INSERT INTO list_weather_rules (id, id_story, id_card, id_text_name, probability, active) VALUES (90003, 9001, 90012, 802, 15, 1);
-- Step 29: inactive, so the roll at time-start can never land on it. An event conditioned on
-- this weather is blocked until an effect sets it — in every run, not just the lucky ones.
INSERT INTO list_weather_rules (id, id_story, id_card, id_text_name, probability, active) VALUES (90004, 9001, 90012, 802, 0, 0);

-- ── Story 1 Events ──────────────────────────────────────────────
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (90001, 9001, 500, 500, 'FIRST', 0, 0);
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (90002, 9001, 501, 501, 'FIRST', 0, 0);
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (90003, 9001, 502, 502, 'FIRST', 0, 0);
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (90004, 9001, 503, 503, 'NORMAL', 1, 0);
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (90005, 9001, 504, 504, 'AUTOMATIC', 0, 1);

-- ── Story 1 Event Effects ───────────────────────────────────────
INSERT INTO list_events_effects (id, id_story, id_event, statistics, value, target) VALUES (90001, 9001, 90001, 'exp', 2, 'ALL');
INSERT INTO list_events_effects (id, id_story, id_event, statistics, value, target) VALUES (90002, 9001, 90002, 'exp', 3, 'ALL');
INSERT INTO list_events_effects (id, id_story, id_event, statistics, value, target) VALUES (90003, 9001, 90003, 'exp', 3, 'ALL');
INSERT INTO list_events_effects (id, id_story, id_event, statistics, value, target) VALUES (90004, 9001, 90004, 'energy', -1, 'ONLY_ONE');
INSERT INTO list_events_effects (id, id_story, id_event, statistics, value, target) VALUES (90005, 9001, 90005, 'exp', 15, 'ALL');

-- ── Step 29 Events — player-triggered actions (mirrors the SQLite seed) ──────
-- Bound to the START location (90001, Welcome Hall) so a fresh match already has
-- executable actions on GET /match/{uuid}/info: one event per branch of the check
-- procedure, plus the "unlocker" that makes each blocked one available.
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90010, 9001, 90001, 503, 503, 90001, 'NORMAL', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90011, 9001, 90001, 503, 503, 90001, 'ONCE', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90012, 9001, 90001, 503, 503, 90001, 'NORMAL', 999, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90013, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 999, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90014, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, 'STEP29_GATE', 'OPEN', NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90015, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, 90002, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90016, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 90002);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90017, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, 90004, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90018, 9001, 90001, 503, 503, 90005, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
-- 90023 is the second link of the 90019 chain: Postgres validates id_event_next on
-- INSERT, so the target row must already exist when 90019 lands.
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90023, 9001, 90001, 503, 503, NULL, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90019, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, 90023, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90020, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90021, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90022, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90024, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90025, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90026, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90027, 9001, 90001, 503, 503, 90001, 'AUTOMATIC', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
-- v0.29.3 teleporter: its effect moves the actor to 90006
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90028, 9001, 90001, 503, 503, 90001, 'NORMAL', 2, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);

-- ── Step 29 Event Effects — one per effect kind. The EFFECT's card is the narrative. ──
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90010, 9001, 90010, 90001, 'exp', 5, 'ONLY_ONE');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90011, 9001, 90010, 90001, 'life', -2, 'ALL');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90012, 9001, 90011, 90001, 'exp', 7, 'ONLY_ONE');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90013, 9001, 90019, 90001, 'exp', 1, 'ONLY_ONE');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90014, 9001, 90023, 90001, 'exp', 2, 'ONLY_ONE');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, target, key_to_add, key_value_to_add) VALUES (90015, 9001, 90020, 90001, 'ONLY_ONE', 'STEP29_GATE', 'OPEN');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, target, id_item_target, item_action) VALUES (90016, 9001, 90021, 90001, 'ONLY_ONE', 90002, 'ADD');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, target, id_weather) VALUES (90017, 9001, 90022, 90001, 'ONLY_ONE', 90004);
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90018, 9001, 90024, 90001, 'energy', -1, 'ONLY_ONE');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, target, traits_to_add, traits_to_remove, characteristic_to_add) VALUES (90019, 9001, 90025, 90001, 'ONLY_ONE', '90001', '90004', 'BRAVE');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90020, 9001, 90026, 90001, 'food', 3, 'ONLY_ONE');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90021, 9001, 90026, 90001, 'magic', 2, 'ONLY_ONE');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90022, 9001, 90026, 90001, 'coin', 9, 'ONLY_ONE');
-- 90028 teleporter (v0.29.3): moves the actor to the Weather Observatory (90006), which is NOT
-- a neighbor of the start location — no checks, no movement cost, only the event's energy cost.
INSERT INTO list_events_effects (id, id_story, id_event, id_card, value, target, id_location) VALUES (90023, 9001, 90028, 90001, 0, 'ONLY_ONE', 90006);

-- v0.34.0 inventory pair: 90050 is gated by item 90003, which 90051 grants. Because 90003
-- is CONSUMABLE, using it must close 90050 again — the step-34 acceptance test. 90052 hands
-- over the Lead Ingot, whose weight is what makes the step-35 OVERWEIGHT refusal reachable.
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90050, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, 90003, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90051, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90052, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target, id_item_target, item_action) VALUES (90050, 9001, 90051, 90001, NULL, 0, 'ONLY_ONE', 90003, 'ADD');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target, id_item_target, item_action) VALUES (90051, 9001, 90051, 90001, NULL, 0, 'ONLY_ONE', 90005, 'ADD');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target, id_item_target, item_action) VALUES (90052, 9001, 90052, 90001, NULL, 0, 'ONLY_ONE', 90006, 'ADD');

-- ── Step 33 Events — the ones nobody asks for ───────────────────
-- Named BY the location through list_locations.id_event_*, so id_specific_location stays
-- NULL and /info never offers them as actions. type='AUTOMATIC' is what the {NORMAL, ONCE}
-- allowlist already refuses to players. None of them owns a choice — an automatic event has
-- nobody to ask and no response to ask in.
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next) VALUES (90040, 9001, 90001, 503, 503, NULL, 'AUTOMATIC', 0, 0, 0, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next) VALUES (90041, 9001, 90001, 503, 503, NULL, 'AUTOMATIC', 0, 0, 0, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next) VALUES (90042, 9001, 90001, 503, 503, NULL, 'AUTOMATIC', 0, 0, 0, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next) VALUES (90043, 9001, 90001, 503, 503, NULL, 'AUTOMATIC', 0, 0, 0, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next) VALUES (90044, 9001, 90001, 503, 503, NULL, 'AUTOMATIC', 0, 0, 0, NULL);

-- One recognisable effect each, so a Robot test can tell which trigger fired (the effect
-- ids mirror their event ids: the 900xx range below 90030 is already spoken for). The
-- counter-zero fuse writes a registry key and nothing else: it must still change the world
-- when it fires in a location nobody is standing in.
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target, key_to_add, key_value_to_add) VALUES (90040, 9001, 90040, 90001, 'exp', 11, 'ONLY_ONE', 'STEP33_FIRST', 'YES');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target, key_to_add, key_value_to_add) VALUES (90041, 9001, 90041, 90001, 'exp', 12, 'ONLY_ONE', 'STEP33_SUBSEQUENT', 'YES');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target, key_to_add, key_value_to_add) VALUES (90042, 9001, 90042, 90001, 'exp', 13, 'ONLY_ONE', 'STEP33_ALONE', 'YES');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target, key_to_add, key_value_to_add) VALUES (90043, 9001, 90043, 90001, NULL, 0, 'ONLY_ONE', 'STEP33_COUNTER', 'YES');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target, key_to_add, key_value_to_add) VALUES (90044, 9001, 90044, 90001, 'exp', 14, 'ONLY_ONE', 'STEP33_STARTTIME', 'YES');

-- ── Step 33 location triggers ───────────────────────────────────
-- 90002 Movement Training Room: the first arrival and every later one differ.
-- 90003 Energy & Life Classroom: fires only when the arriving character finds it empty.
-- 90001 Welcome Hall: the start, which already carries counter_time = 2, so its fuse burns
--       down over two time-starts and finally executes something (Step 26 only logged it).
-- 90004 Item Workshop: a time unit BEGINNING with somebody standing there.
UPDATE list_locations SET id_event_if_first_time = 90040, id_event_not_first_time = 90041 WHERE id = 90002 AND id_story = 9001;
UPDATE list_locations SET id_event_if_character_enter_empty_location = 90042 WHERE id = 90003 AND id_story = 9001;
UPDATE list_locations SET id_event_if_counter_zero = 90043, priority_automatic_event = 1 WHERE id = 90001 AND id_story = 9001;
UPDATE list_locations SET id_event_if_character_start_time = 90044, priority_automatic_event = 2 WHERE id = 90004 AND id_story = 9001;

-- ── Story 1 Choices ─────────────────────────────────────────────
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress) VALUES (90001, 9001, 90004, 1, 600, 600, 0, 1);
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress) VALUES (90002, 9001, 90004, 2, 601, 601, 0, 1);
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress) VALUES (90003, 9001, 90003, 1, 602, 602, 0, 1);
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress) VALUES (90004, 9001, 90005, 1, 603, 603, 0, 1);

-- ── Story 1 Choice Conditions ───────────────────────────────────
INSERT INTO list_choices_conditions (id, id_story, id_choices, type, key, value, operator) VALUES (90001, 9001, 90003, 'statistics', 'int', '1', '>');

-- ── Story 1 Choice Effects ──────────────────────────────────────
INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90001, 9001, 90001, 'exp', 5);
INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90002, 9001, 90002, 'life', -1);
INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90003, 9001, 90003, 'exp', 3);
INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90004, 9001, 90004, 'exp', 10);

-- ── Step 31 Choice pack — the choice-engine test-bed ────────────
-- Two choice-events at the START location (90001): executing them answers
-- CHOICES_PENDING — cost paid, marker written, effects withheld. Event 90030 even
-- carries an effect row that must NEVER run in Step 31; 90031 is ONCE.
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90180, 9001, 610, 'en', 'Crossroads Trial', 'A hooded figure blocks the path and fans out four cards. "Every road costs something. Choose — or walk away; the toll stays paid."');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90181, 9001, 610, 'it', 'La Prova del Bivio', 'Una figura incappucciata sbarra la strada e apre quattro carte a ventaglio. "Ogni strada ha un prezzo. Scegli — o vattene: il pedaggio resta pagato."');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90182, 9001, 611, 'en', 'Sealed Gate', 'A gate that opens for each traveler exactly once. Beyond it, two paths.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90183, 9001, 611, 'it', 'Il Cancello Sigillato', 'Un cancello che si apre una sola volta per viandante. Oltre, due sentieri.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90184, 9001, 612, 'en', 'Take the plain road', 'No requirement: anyone may walk it.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90185, 9001, 612, 'it', 'Prendi la via semplice', 'Nessun requisito: chiunque può percorrerla.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90186, 9001, 613, 'en', 'Recite the ancient runes', 'Only a prodigious mind (INT above 99) can read them.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90187, 9001, 613, 'it', 'Recita le rune antiche', 'Solo una mente prodigiosa (INT oltre 99) può leggerle.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90188, 9001, 614, 'en', 'Bargain with the figure', 'The gate key OR a beating heart will do.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90189, 9001, 614, 'it', 'Contratta con la figura', 'Basta la chiave del cancello O un cuore che batte.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90190, 9001, 615, 'en', 'Shrug and improvise', 'The fallback nobody can be denied.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90191, 9001, 615, 'it', 'Alza le spalle e improvvisa', 'Il ripiego che non si nega a nessuno.');

INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time) VALUES (90030, 9001, 90001, 610, 610, 90001, 'NORMAL', 2, 0, 0);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time) VALUES (90031, 9001, 90001, 611, 611, 90001, 'ONCE', 1, 0, 0);

INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90024, 9001, 90030, 90001, 'exp', 99, 'ONLY_ONE');

INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90010, 9001, 90030, 2, 612, 612, 0, 0, 'AND', NULL);
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90011, 9001, 90030, 1, 613, 613, 0, 0, 'AND', NULL);
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90012, 9001, 90030, 3, 614, 614, 0, 0, 'OR', NULL);
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90013, 9001, 90030, 4, 615, 615, 1, 0, 'AND', 99);
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90014, 9001, 90031, 1, 612, 612, 0, 0, 'AND', NULL);
INSERT INTO list_choices (id, id_story, id_event, priority, id_text_name, id_text_description, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90015, 9001, 90031, 2, 613, 613, 0, 0, 'AND', 99);

INSERT INTO list_choices_conditions (id, id_story, id_choices, type, key, value, operator) VALUES (90002, 9001, 90011, 'statistics', 'int', '99', '>');
INSERT INTO list_choices_conditions (id, id_story, id_choices, type, key, value, operator) VALUES (90003, 9001, 90012, 'KEYS', 'STEP29_GATE', 'OPEN', '=');
INSERT INTO list_choices_conditions (id, id_story, id_choices, type, key, value, operator) VALUES (90004, 9001, 90012, 'statistics', 'life', '0', '>');

INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90005, 9001, 90010, 'energy', 1);
INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90006, 9001, 90011, 'life', 1);
INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90007, 9001, 90012, 'exp', 2);
INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90008, 9001, 90014, 'energy', 1);
INSERT INTO list_choices_effects (id, id_story, id_choices, statistics, value) VALUES (90009, 9001, 90015, 'life', 1);

-- ── Step 32 Resolution pack — what a selected option does ───────
-- Event 90032 at the START location is the resolution test-bed: opening it costs 3
-- (unambiguous for the robot lookup), resolving any of its options costs nothing at all.
-- 90033 is the outcome event one option runs: it lives nowhere and costs 9, proving a
-- consequence is neither re-checked nor charged.
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90192, 9001, 616, 'en', 'The Fork', 'The road splits. One way is yours alone; the other follows a lantern that is already moving.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90193, 9001, 616, 'it', 'Il Bivio', 'La strada si divide. Una via è solo tua; l''altra segue una lanterna che si sta già muovendo.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90194, 9001, 617, 'en', 'Beyond The Fork', 'Whatever the lantern was, it left something behind.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90195, 9001, 617, 'it', 'Oltre Il Bivio', 'Qualunque cosa fosse la lanterna, ha lasciato qualcosa.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90196, 9001, 618, 'en', 'Press on alone', 'Costs nothing to choose; the toll was paid at the fork.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90197, 9001, 618, 'it', 'Prosegui da solo', 'Scegliere non costa nulla: il pedaggio è stato pagato al bivio.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90198, 9001, 619, 'en', 'Follow the lantern', 'It grants, it moves, it changes the sky — and it opens a door.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (90199, 9001, 619, 'it', 'Segui la lanterna', 'Dona, sposta, cambia il cielo — e apre una porta.');
-- The narratives: withheld while the options are pending, revealed by the resolution.
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91210, 9001, 620, 'en', 'You walk on, and the fork closes behind you.', NULL);
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91211, 9001, 620, 'it', 'Prosegui, e il bivio si chiude alle tue spalle.', NULL);
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91212, 9001, 621, 'en', 'The lantern leads you into the grove.', NULL);
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91213, 9001, 621, 'it', 'La lanterna ti conduce nel bosco.', NULL);

INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time) VALUES (90032, 9001, 90001, 616, 616, 90001, 'NORMAL', 3, 0, 0);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time) VALUES (90033, 9001, 90001, 617, 617, NULL, 'NORMAL', 9, 0, 0);

INSERT INTO list_events_effects (id, id_story, id_event, id_card, statistics, value, target) VALUES (90025, 9001, 90033, 90001, 'exp', 7, 'ONLY_ONE');

-- id_card is set on every option: the resolution answers with the choice's own card.
INSERT INTO list_choices (id, id_story, id_card, id_event, priority, id_text_name, id_text_description, id_text_narrative, id_event_torun, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90020, 9001, 90001, 90032, 1, 618, 618, 620, NULL, 0, 1, 'AND', NULL);
INSERT INTO list_choices (id, id_story, id_card, id_event, priority, id_text_name, id_text_description, id_text_narrative, id_event_torun, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90021, 9001, 90001, 90032, 2, 619, 619, 621, 90033, 0, 0, 'AND', NULL);
INSERT INTO list_choices (id, id_story, id_card, id_event, priority, id_text_name, id_text_description, id_text_narrative, id_event_torun, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90022, 9001, 90001, 90032, 3, 613, 613, NULL, NULL, 0, 0, 'AND', 99);

-- id_event is the EFFECT-level link ("Event to Run (effect)"), distinct from the
-- choice-level id_event_torun option 90021 uses: both mechanisms are seeded.
INSERT INTO list_choices_effects (id, id_story, id_choices, id_card, statistics, value, id_event) VALUES (90020, 9001, 90020, 90001, 'exp', 5, 90033);
-- One row, every kind of effect: a registry key, an item, a forced move to the Hidden
-- Grove (90003, which no neighbor edge reaches), and the inactive Arcane Storm (90004).
INSERT INTO list_choices_effects (id, id_story, id_choices, id_card, key, value_to_add, id_item_target, item_action, id_location, id_weather) VALUES (90021, 9001, 90021, 90001, 'STEP32_GATE', 'OPEN', 90001, 'ADD', 90003, 90004);

-- ── Step 36.1 multi-value pack — the SET test-bed ───────────────
-- Four events at the START hall (90001), every one of them FREE. A zero cost is what keeps
-- them invisible to the Step 31/32 finders, which only ever pick a choice-event that costs
-- something: this pack must not become the fixture those suites address by behaviour.
--   90360 / 90361  add one member each to the multi key, and are repeatable — running one
--                  twice must leave the set unchanged, which is the whole point of a SET.
--   90362          is gated on evidence_found = letter, so it stays blocked until 90361 has
--                  run: it proves = quantifies EXISTENTIALLY over the members.
--   90363          is a choice-event whose only option TAKES ONE MEMBER AWAY — value_to_remove
--                  on a multi key removes that member and leaves the rest.
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90360, 9001, 90001, 500, 500, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90361, 9001, 90001, 500, 500, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90362, 9001, 90001, 500, 500, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, 'evidence_found', 'letter', NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, id_item_condition, id_class_condition) VALUES (90363, 9001, 90001, 500, 500, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO list_events_effects (id, id_story, id_event, id_card, target, key_to_add, key_value_to_add) VALUES (90360, 9001, 90360, 90001, 'ONLY_ONE', 'evidence_found', 'ledger');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, target, key_to_add, key_value_to_add) VALUES (90361, 9001, 90361, 90001, 'ONLY_ONE', 'evidence_found', 'letter');

-- otherwise_flag 1 and no narrative: always selectable, and never the option the Step 32
-- suite is looking for (it wants a narrated one).
INSERT INTO list_choices (id, id_story, id_card, id_event, priority, id_text_name, id_text_description, id_text_narrative, id_event_torun, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90360, 9001, 90001, 90363, 1, 500, 500, NULL, NULL, 1, 0, 'AND', NULL);

INSERT INTO list_choices_effects (id, id_story, id_choices, id_card, key, value_to_remove) VALUES (90360, 9001, 90360, 90001, 'evidence_found', 'ledger');

-- v0.36.1 — a SECOND option on the same event, gated on the multi key with !=, so one open
-- shows both readings: offered while the set does not hold the value, refused once it does.
-- otherwise_flag 0 (a real verdict) and an effect of its own, as R4_CHOICE_EMPTY requires.
INSERT INTO list_choices (id, id_story, id_card, id_event, priority, id_text_name, id_text_description, id_text_narrative, id_event_torun, otherwise_flag, is_progress, logic_operator, limit_dex) VALUES (90361, 9001, 90001, 90363, 2, 500, 500, NULL, NULL, 0, 0, 'AND', NULL);
INSERT INTO list_choices_conditions (id, id_story, id_choices, type, key, value, operator) VALUES (90360, 9001, 90361, 'KEYS', 'evidence_found', 'ledger', '!=');
INSERT INTO list_choices_effects (id, id_story, id_choices, id_card, statistics, value) VALUES (90361, 9001, 90361, 90001, 'exp', 1);

-- ── Step 36.2 case-and-padding pack — spelling must not decide a gate ───
-- Four more FREE events at the START hall (90001), for the same reason as the 36.1 pack:
-- a zero cost keeps them invisible to the Step 31/32 finders.
--   90370  WRITES ' Ledger ' — padded and capitalised, exactly as a careless author writes.
--   90371  READS  'ledger'   — bare and lowercase. It must open once 90370 has run, which
--                              is the whole claim of v0.36.2 in one pair of rows.
--   90372  WRITES 'LEDGER'   — a third spelling of the member the set already holds. The set
--                              must stay at one member: a duplicate is not a new value.
--   90373  READS  '  GREEN ' — the mirror direction: a padded, upper-case condition against
--                              the lowercase default 'signal' carries from list_keys.
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, registry_value_operator_condition, id_item_condition, id_class_condition) VALUES (90370, 9001, 90001, 500, 500, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, '=', NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, registry_value_operator_condition, id_item_condition, id_class_condition) VALUES (90371, 9001, 90001, 500, 500, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, 'case_notes', 'ledger', '=', NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, registry_value_operator_condition, id_item_condition, id_class_condition) VALUES (90372, 9001, 90001, 500, 500, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, NULL, NULL, '=', NULL, NULL);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, flag_end_time, id_event_next, id_weather, registry_key_condition, registry_value_condition, registry_value_operator_condition, id_item_condition, id_class_condition) VALUES (90373, 9001, 90001, 500, 500, 90001, 'NORMAL', 0, 0, 0, NULL, NULL, 'signal', '  GREEN  ', '=', NULL, NULL);

INSERT INTO list_events_effects (id, id_story, id_event, id_card, target, key_to_add, key_value_to_add) VALUES (90370, 9001, 90370, 90001, 'ONLY_ONE', 'case_notes', ' Ledger ');
INSERT INTO list_events_effects (id, id_story, id_event, id_card, target, key_to_add, key_value_to_add) VALUES (90372, 9001, 90372, 90001, 'ONLY_ONE', 'case_notes', 'LEDGER');

-- ── Story 1 Global Random Events ────────────────────────────────
INSERT INTO list_global_random_events (id, id_story, probability) VALUES (90001, 9001, 10);

-- ── Story 1 Missions ────────────────────────────────────────────
INSERT INTO list_missions (id, id_story, condition_key, condition_value_from, condition_value_to, id_text_name, id_text_description) VALUES (90001, 9001, 'tutorial_progress', '0', '3', 900, 900);
INSERT INTO list_missions (id, id_story, condition_key, condition_value_to, id_text_name, id_text_description) VALUES (90002, 9001, 'items_collected', '1', 901, 901);
INSERT INTO list_missions (id, id_story, condition_key, condition_value_to, id_text_name, id_text_description) VALUES (90003, 9001, 'choice_made', 'gold', 902, 902);

-- ── Story 1 Mission Steps ───────────────────────────────────────
INSERT INTO list_missions_steps (id, id_story, id_mission, step, condition_key, condition_value_to) VALUES (90001, 9001, 90001, 1, 'visited_movement', '1');
INSERT INTO list_missions_steps (id, id_story, id_mission, step, condition_key, condition_value_to) VALUES (90002, 9001, 90001, 2, 'visited_energy', '1');
INSERT INTO list_missions_steps (id, id_story, id_mission, step, condition_key, condition_value_to) VALUES (90003, 9001, 90001, 3, 'visited_graduation', '1');
INSERT INTO list_missions_steps (id, id_story, id_mission, step, condition_key, condition_value_to) VALUES (90004, 9001, 90002, 1, 'potion_collected', '1');
INSERT INTO list_missions_steps (id, id_story, id_mission, step, condition_key, condition_value_to) VALUES (90005, 9001, 90002, 2, 'snack_used', '1');
INSERT INTO list_missions_steps (id, id_story, id_mission, step, condition_key, condition_value_to) VALUES (90006, 9001, 90003, 1, 'entered_arena', '1');
INSERT INTO list_missions_steps (id, id_story, id_mission, step, condition_key, condition_value_to) VALUES (90007, 9001, 90003, 2, 'door_chosen', '1');

-- ── Story 1 Creator ─────────────────────────────────────────────
INSERT INTO list_creator (id, id_story, link) VALUES (90001, 9001, 'https://paths.games');

-- (Story 1 Cards are inserted before Story 1 Locations so the
--  fk_locations_card composite FK (id_card, id_story) is satisfied.)

-- #############################################################################
-- STORY 2: IL VALVASSORE DI MARCA (id=9002)
-- #############################################################################

-- ── Story 2 Texts ───────────────────────────────────────────────
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91001, 9002, 1, 'en', 'The Valvassor of the March', 'Veneto, 1243 AD. You are a valvassor serving under Ezzelino III da Romano.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91002, 9002, 1, 'it', 'Il Valvassore di Marca', 'Veneto, 1243. Sei un valvassore al servizio di Ezzelino III da Romano.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91003, 9002, 2, 'en', 'The Valvassor of the March', 'Travel across medieval Veneto to save your vassal from an unjust death.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91004, 9002, 2, 'it', 'Il Valvassore di Marca', 'Viaggia attraverso il Veneto medievale per salvare il tuo vassallo.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91005, 9002, 100, 'en', 'Castelfranco Veneto', 'Your small fortified town.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91006, 9002, 100, 'it', 'Castelfranco Veneto', 'La tua piccola città fortificata.');
-- v0.28.7 — location and weather card titles for story 2 (locations 91002..91004
-- reference id_text 101..103; weather cards 91010..91012 reference id_text 800..802).
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91200, 9002, 101, 'en', 'Treviso', 'The seat of the March, busy with merchants and clerks.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91201, 9002, 101, 'it', 'Treviso', 'La sede della Marca, affollata di mercanti e scrivani.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91202, 9002, 102, 'en', 'The Court of Justice', 'Where your vassal will be judged.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91203, 9002, 102, 'it', 'La Corte di Giustizia', 'Dove il tuo vassallo sarà giudicato.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91204, 9002, 800, 'en', 'Clear Sky', 'A bright day over the March.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91205, 9002, 800, 'it', 'Cielo Sereno', 'Una giornata limpida sulla Marca.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91206, 9002, 801, 'en', 'Fog', 'The plain disappears under a thick fog.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91207, 9002, 801, 'it', 'Nebbia', 'La pianura scompare sotto una fitta nebbia.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91208, 9002, 802, 'en', 'Storm', 'A storm sweeps the roads of the March.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91209, 9002, 802, 'it', 'Tempesta', 'Una tempesta spazza le strade della Marca.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91029, 9002, 200, 'en', 'Knight', 'A minor noble trained in combat and horsemanship.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91030, 9002, 200, 'it', 'Cavaliere', 'Un piccolo nobile addestrato nel combattimento.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91031, 9002, 201, 'en', 'Cleric', 'A man of the cloth with access to monasteries.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91032, 9002, 201, 'it', 'Chierico', 'Un uomo di chiesa.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91033, 9002, 202, 'en', 'Merchant', 'A wealthy trader with connections in every city.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91034, 9002, 202, 'it', 'Mercante', 'Un ricco commerciante.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91035, 9002, 203, 'en', 'Scout', 'A nimble tracker at home in forests and marshes.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91036, 9002, 203, 'it', 'Esploratore', 'Un agile segugi.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91037, 9002, 300, 'en', 'Merciful Judge', 'Extra time and resources.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91038, 9002, 300, 'it', 'Giudice Misericordioso', 'Tempo e risorse extra.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91039, 9002, 301, 'en', 'Just Trial', 'Standard difficulty.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91040, 9002, 301, 'it', 'Giusto Processo', 'Difficoltà standard.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91041, 9002, 302, 'en', 'Iron Inquisition', 'Extreme difficulty.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91042, 9002, 302, 'it', 'Inquisizione di Ferro', 'Difficoltà estrema.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91073, 9002, 700, 'en', 'Feudal Authority', 'Your rank commands respect from peasants and minor lords.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91074, 9002, 700, 'it', 'Autorità Feudale', 'Il tuo rango impone rispetto.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91075, 9002, 701, 'en', 'Silver Tongue', 'A gift for persuasion.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91076, 9002, 701, 'it', 'Lingua d''Argento', 'Un dono per la persuasione.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91077, 9002, 702, 'en', 'Local Knowledge', 'Born and raised in the Marca Trevigiana.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91078, 9002, 702, 'it', 'Conoscenza del Territorio', 'Nato e cresciuto nella Marca Trevigiana.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91098, 9002, 210, 'en', 'The Loyal Valvassor', 'A steadfast minor lord who always honors his oaths.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91099, 9002, 211, 'en', 'The Cunning Notary', 'A sharp legal mind trained at the University of Padova.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91100, 9002, 212, 'en', 'The Veteran Sergeant', 'A battle-hardened soldier from Ezzelino''s campaigns.');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91104, 9002, 10, 'it', 'ora', 'ora');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91105, 9002, 11, 'it', 'ore', 'ore');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91106, 9002, 10, 'en', 'hour', 'hour');
INSERT INTO list_texts (id, id_story, id_text, lang, short_text, long_text) VALUES (91107, 9002, 11, 'en', 'hours', 'hours');

-- ── Story 2 Difficulties ────────────────────────────────────────
INSERT INTO list_stories_difficulty (id, id_story, id_text_description, exp_cost, max_weight, min_character, max_character, cost_help_coma, cost_max_characteristics, number_max_free_action, life, energy, sad, dexterity, intelligence, constitution, weight) VALUES (91001, 9002, 300, 3, 20, 1, 4, 2, 2, 3, 130, 120, 0, 12, 12, 14, 14);
INSERT INTO list_stories_difficulty (id, id_story, id_text_description, exp_cost, max_weight, min_character, max_character, cost_help_coma, cost_max_characteristics, number_max_free_action, life, energy, sad, dexterity, intelligence, constitution, weight) VALUES (91002, 9002, 301, 5, 12, 1, 4, 3, 3, 1, 100, 100, 10, 10, 10, 10, 10);
INSERT INTO list_stories_difficulty (id, id_story, id_text_description, exp_cost, max_weight, min_character, max_character, cost_help_coma, cost_max_characteristics, number_max_free_action, life, energy, sad, dexterity, intelligence, constitution, weight) VALUES (91003, 9002, 302, 8, 8, 2, 3, 5, 5, 0, 80, 90, 20, 8, 8, 8, 8);

-- ── Story 2 Classes ─────────────────────────────────────────────
INSERT INTO list_classes (id, id_story, id_text_name, id_text_description, weight_max, dexterity_base, intelligence_base, constitution_base) VALUES (91001, 9002, 200, 200, 12, 3, 2, 4);
INSERT INTO list_classes (id, id_story, id_text_name, id_text_description, weight_max, dexterity_base, intelligence_base, constitution_base) VALUES (91002, 9002, 201, 201, 6, 1, 5, 2);
INSERT INTO list_classes (id, id_story, id_text_name, id_text_description, weight_max, dexterity_base, intelligence_base, constitution_base) VALUES (91003, 9002, 202, 202, 10, 2, 4, 2);
INSERT INTO list_classes (id, id_story, id_text_name, id_text_description, weight_max, dexterity_base, intelligence_base, constitution_base) VALUES (91004, 9002, 203, 203, 8, 5, 2, 2);

-- ── Story 2 Traits ──────────────────────────────────────────────
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight) VALUES (91001, 9002, 700, 700, 3, 0,  3, 0, 0, 0, 0, 2, 0);
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight) VALUES (91002, 9002, 701, 701, 2, 0,  0, 3, 0, 2, 0, 0, 0);
INSERT INTO list_traits (id, id_story, id_text_name, id_text_description, cost_positive, cost_negative, life, energy, sad, dexterity, intelligence, constitution, weight) VALUES (91003, 9002, 702, 702, 2, 0,  0, 0, 0, 0, 3, 0, 2);

-- ── Story 2 Character Templates ─────────────────────────────────
INSERT INTO list_character_templates (id_tipo, id_story, id_text_name, id_text_description, life_max, energy_max, sad_max, dexterity_start, intelligence_start, constitution_start, id_class_permitted, id_class_prohibited) VALUES (91001, 9002, 210, 210, 12, 10, 8, 3, 3, 4, NULL,  NULL);
INSERT INTO list_character_templates (id_tipo, id_story, id_text_name, id_text_description, life_max, energy_max, sad_max, dexterity_start, intelligence_start, constitution_start, id_class_permitted, id_class_prohibited) VALUES (91002, 9002, 211, 211, 8, 8, 6, 1, 5, 2, 91002, NULL);
INSERT INTO list_character_templates (id_tipo, id_story, id_text_name, id_text_description, life_max, energy_max, sad_max, dexterity_start, intelligence_start, constitution_start, id_class_permitted, id_class_prohibited) VALUES (91003, 9002, 212, 212, 14, 12, 10, 4, 1, 5, NULL,  91001);

-- ── Story 2 Cards ───────────────────────────────────────────────
-- Inserted before locations: fk_locations_card (id_card, id_story) requires the card to exist.
INSERT INTO list_cards (id, id_story, url_immage, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (91001, 9002, 'https://paths.games/assets/cards/valvassore.jpg', 'fas fa-chess-rook', 'medieval', 1, 2, 1);
-- v0.28.7: these two cards back locations 91002..91004; they need a title so the
-- location card resolves with one (match logs, locations API, admin console).
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (91002, 9002, 'fas fa-scroll', 'evidence', 101, 101, 101);
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (91003, 9002, 'fas fa-balance-scale', 'justice', 102, 102, 102);
-- Step 27 — weather cards for story 9002
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (91010, 9002, 'fas fa-sun', 'weather', 800, 800, 800);
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (91011, 9002, 'fas fa-smog', 'weather', 801, 801, 801);
INSERT INTO list_cards (id, id_story, awesome_icon, style_main, id_text_title, id_text_description, id_text_name) VALUES (91012, 9002, 'fas fa-cloud-bolt', 'weather', 802, 802, 802);

-- ── Story 2 Locations ───────────────────────────────────────────
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91001, 9002, 91001, 100, 100, 1, 10);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91002, 9002, 91002, 101, 101, 1, 15);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91003, 9002, 91003, 102, 102, 1, 20);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91004, 9002, 91002, 103, 103, 0, 8);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91005, 9002, 91001, 104, 104, 1, 6);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91006, 9002, 91002, 105, 105, 1, 10);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91007, 9002, 91003, 106, 106, 0, 4);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91008, 9002, 91002, 107, 107, 0, 6);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91009, 9002, 91003, 108, 108, 0, 4);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91010, 9002, 91001, 109, 109, 0, 12);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91011, 9002, 91002, 110, 110, 0, 6);
INSERT INTO list_locations (id, id_story, id_card, id_text_name, id_text_description, is_safe, max_characters) VALUES (91012, 9002, 91003, 111, 111, 1, 8);

-- ── Story 2 Events ──────────────────────────────────────────────
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (91001, 9002, 500, 500, 'NORMAL', 2, 0);
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (91002, 9002, 501, 501, 'NORMAL', 1, 0);
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (91003, 9002, 502, 502, 'FIRST', 0, 0);
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (91004, 9002, 503, 503, 'NORMAL', 1, 0);
INSERT INTO list_events (id, id_story, id_text_name, id_text_description, type, cost_enery, flag_end_time) VALUES (91005, 9002, 504, 504, 'AUTOMATIC', 0, 1);

-- v0.35.3 resource costs: the twins of 90013 (cost_coin 999) for the two new refusals,
-- plus one event a topped-up backpack can actually afford.
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, cost_food, cost_magic, flag_end_time) VALUES (90053, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 999, 0, 0);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, cost_food, cost_magic, flag_end_time) VALUES (90054, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 0, 0, 999, 0);
INSERT INTO list_events (id, id_story, id_card, id_text_name, id_text_description, id_specific_location, type, cost_enery, cost_coin, cost_food, cost_magic, flag_end_time) VALUES (90055, 9001, 90001, 503, 503, 90001, 'NORMAL', 0, 1, 2, 1, 0);

-- ── Story 2 Items ───────────────────────────────────────────────
INSERT INTO list_items (id, id_story, id_text_name, id_text_description, weight) VALUES (91001, 9002, 400, 400, 1);
INSERT INTO list_items (id, id_story, id_text_name, id_text_description, weight) VALUES (91002, 9002, 401, 401, 1);
INSERT INTO list_items (id, id_story, id_text_name, id_text_description, weight) VALUES (91003, 9002, 402, 402, 2);
INSERT INTO list_items (id, id_story, id_text_name, id_text_description, weight) VALUES (91004, 9002, 403, 403, 1);
INSERT INTO list_items (id, id_story, id_text_name, id_text_description, weight) VALUES (91005, 9002, 404, 404, 1);

-- ── Story 1 Item Effects ────────────────────────────────────────
-- (Story 1 item effects with correct column names)
INSERT INTO list_items_effects (id, id_story, id_item, effect_code, effect_value) VALUES (91001, 9002, 91001, 'LIFE', 3);
INSERT INTO list_items_effects (id, id_story, id_item, effect_code, effect_value) VALUES (91002, 9002, 91003, 'EXP', 5);
INSERT INTO list_items_effects (id, id_story, id_item, effect_code, effect_value) VALUES (91003, 9002, 91004, 'ENERGY', 3);

-- ── Story 2 Cards ───────────────────────────────────────────────
-- (Card INSERTs moved before Story 2 Locations for the fk_locations_card FK.)
UPDATE list_stories SET id_card = 91001 WHERE id = 9002;
UPDATE list_stories SET id_card = 90001 WHERE id = 9001;

-- ── Story 2 Creator ─────────────────────────────────────────────
INSERT INTO list_creator (id, id_story, link) VALUES (91001, 9002, 'https://paths.games');

-- Reset sequences after explicit ID inserts for story seed data
SELECT setval('list_stories_id_seq',            (SELECT MAX(id) FROM list_stories));
SELECT setval('list_texts_id_seq',              (SELECT MAX(id) FROM list_texts));
SELECT setval('list_classes_id_seq',            (SELECT MAX(id) FROM list_classes));
SELECT setval('list_classes_bonus_id_seq',      (SELECT MAX(id) FROM list_classes_bonus));
SELECT setval('list_traits_id_seq',             (SELECT MAX(id) FROM list_traits));
SELECT setval('list_keys_id_seq',               (SELECT MAX(id) FROM list_keys));
SELECT setval('list_locations_id_seq',          (SELECT MAX(id) FROM list_locations));
SELECT setval('list_locations_neighbors_id_seq',(SELECT MAX(id) FROM list_locations_neighbors));
SELECT setval('list_items_id_seq',              (SELECT MAX(id) FROM list_items));
SELECT setval('list_items_effects_id_seq',      (SELECT MAX(id) FROM list_items_effects));
SELECT setval('list_weather_rules_id_seq',      (SELECT MAX(id) FROM list_weather_rules));
SELECT setval('list_events_id_seq',             (SELECT MAX(id) FROM list_events));
SELECT setval('list_events_effects_id_seq',     (SELECT MAX(id) FROM list_events_effects));
SELECT setval('list_choices_id_seq',            (SELECT MAX(id) FROM list_choices));
SELECT setval('list_choices_conditions_id_seq', (SELECT MAX(id) FROM list_choices_conditions));
SELECT setval('list_choices_effects_id_seq',    (SELECT MAX(id) FROM list_choices_effects));
SELECT setval('list_global_random_events_id_seq',(SELECT MAX(id) FROM list_global_random_events));
SELECT setval('list_missions_id_seq',           (SELECT MAX(id) FROM list_missions));
SELECT setval('list_missions_steps_id_seq',     (SELECT MAX(id) FROM list_missions_steps));
SELECT setval('list_creator_id_seq',            (SELECT MAX(id) FROM list_creator));
SELECT setval('list_cards_id_seq',              (SELECT MAX(id) FROM list_cards));

-- ── Step 27.x / 0.25.4 — match-info locationsActive wiring ──────
-- Set the start location (so a joined character has idLocation), mark the
-- end-game event and pin it to a location, so GET /api/match/{uuid}/info
-- returns a populated locationsActive with an event flagged endGame=true.
UPDATE list_stories SET id_location_start = 90001, id_event_end_game = 90005 WHERE id = 9001;
UPDATE list_stories SET id_location_start = 91001, id_event_end_game = 91005 WHERE id = 9002;
UPDATE list_events  SET id_specific_location = 90001 WHERE id = 90005 AND id_story = 9001;
UPDATE list_events  SET id_specific_location = 91001 WHERE id = 91005 AND id_story = 9002;
