-- =============================================
-- Paths Games - Database Schema V0.10.5
-- Story Content Tables (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: list_creator, list_cards, list_texts
-- Reference: Step 09 - Design Core Data Model (Section 1.3)
-- Naming:   Step 06 - Naming Conventions (prefix: list_)
-- =============================================
-- Note: list_creator is created first because list_cards
--       and list_texts reference it via id_creator FK.
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE list_creator (
    id            BIGSERIAL    PRIMARY KEY,
    uuid          UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    id_story      BIGINT       REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text       BIGINT,                                        -- references list_texts(id_text)
    link          TEXT,
    url           TEXT,
    url_image     TEXT,
    url_emote     TEXT,
    url_instagram TEXT,
    ts_insert     TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update     TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE list_cards (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    id_story            BIGINT       REFERENCES list_stories(id) ON DELETE CASCADE,
    url_immage          TEXT,
    id_text_title       BIGINT,                                  -- references list_texts(id_text)
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    id_text_copyright   BIGINT,                                  -- references list_texts(id_text)
    link_copyright      TEXT,
    id_creator          BIGINT       REFERENCES list_creator(id),
    alternative_image   TEXT,
    awesome_icon        VARCHAR(100),
    style_main          VARCHAR(100),
    style_detail        VARCHAR(100),
    ts_insert           TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update           TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE list_texts (
    id                BIGSERIAL    PRIMARY KEY,
    uuid              UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    id_story          BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text           BIGINT       NOT NULL,
    lang              VARCHAR(10)  NOT NULL DEFAULT 'en',
    short_text        VARCHAR(500),
    long_text         TEXT,
    id_text_copyright BIGINT,                                    -- references list_texts(id_text)
    link_copyright    TEXT,
    id_creator        BIGINT       REFERENCES list_creator(id),
    ts_insert         TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update         TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE (id_story, id_text, lang)
);
