-- =============================================
-- Paths Games - Database Schema V0.10.11
-- Indexes & Deferred Foreign Keys (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- This migration adds:
--   1. Deferred FK constraints for circular references
--   2. Performance indexes for frequently-queried columns
-- Reference: Step 09 - Design Core Data Model
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================



-- =============================================
-- PART 1: Deferred Foreign Key Constraints
-- =============================================
-- These FKs reference tables that did not exist at the time
-- the parent table was created. They are added here via ALTER TABLE.

-- list_stories → list_cards, list_locations, list_events, list_creator
ALTER TABLE list_stories ADD CONSTRAINT fk_stories_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_stories ADD CONSTRAINT fk_stories_location_start
    FOREIGN KEY (id_location_start) REFERENCES list_locations(id);
ALTER TABLE list_stories ADD CONSTRAINT fk_stories_location_coma
    FOREIGN KEY (id_location_all_player_coma) REFERENCES list_locations(id);
ALTER TABLE list_stories ADD CONSTRAINT fk_stories_event_coma
    FOREIGN KEY (id_event_all_player_coma) REFERENCES list_events(id);
ALTER TABLE list_stories ADD CONSTRAINT fk_stories_event_end
    FOREIGN KEY (id_event_end_game) REFERENCES list_events(id);
ALTER TABLE list_stories ADD CONSTRAINT fk_stories_creator
    FOREIGN KEY (id_creator) REFERENCES list_creator(id);

-- list_locations → list_events (event trigger columns)
ALTER TABLE list_locations ADD CONSTRAINT fk_locations_event_counter_zero
    FOREIGN KEY (id_event_if_counter_zero) REFERENCES list_events(id);
ALTER TABLE list_locations ADD CONSTRAINT fk_locations_event_start_time
    FOREIGN KEY (id_event_if_character_start_time) REFERENCES list_events(id);
ALTER TABLE list_locations ADD CONSTRAINT fk_locations_event_enter_first
    FOREIGN KEY (id_event_if_character_enter_first_time) REFERENCES list_events(id);
ALTER TABLE list_locations ADD CONSTRAINT fk_locations_event_first_time
    FOREIGN KEY (id_event_if_first_time) REFERENCES list_events(id);
ALTER TABLE list_locations ADD CONSTRAINT fk_locations_event_not_first
    FOREIGN KEY (id_event_not_first_time) REFERENCES list_events(id);

-- list_weather_rules → list_events
ALTER TABLE list_weather_rules ADD CONSTRAINT fk_weather_rules_event
    FOREIGN KEY (id_event) REFERENCES list_events(id);

-- gaming_match → gaming_character_instance (current turn)
ALTER TABLE gaming_match ADD CONSTRAINT fk_match_character_current_turn
    FOREIGN KEY (id_character_current_turn) REFERENCES gaming_character_instance(id);

-- id_card FK columns → list_cards(id)
ALTER TABLE list_stories_difficulty ADD CONSTRAINT fk_stories_diff_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_keys ADD CONSTRAINT fk_keys_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_classes ADD CONSTRAINT fk_classes_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_classes_bonus ADD CONSTRAINT fk_classes_bonus_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_traits ADD CONSTRAINT fk_traits_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_character_templates ADD CONSTRAINT fk_char_templates_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_locations ADD CONSTRAINT fk_locations_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_items ADD CONSTRAINT fk_items_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_weather_rules ADD CONSTRAINT fk_weather_rules_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_events ADD CONSTRAINT fk_events_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_events_effects ADD CONSTRAINT fk_events_effects_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_choices ADD CONSTRAINT fk_choices_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_global_random_events ADD CONSTRAINT fk_global_random_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_missions ADD CONSTRAINT fk_missions_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);
ALTER TABLE list_missions_steps ADD CONSTRAINT fk_missions_steps_card
    FOREIGN KEY (id_card) REFERENCES list_cards(id);


-- =============================================
-- PART 2: Performance Indexes
-- =============================================

-- System
CREATE INDEX idx_global_runtime_vars_key ON global_runtime_variables(key);

-- Users
CREATE INDEX idx_users_email          ON users(email_address);
CREATE INDEX idx_users_google_sso     ON users(google_id_sso);
CREATE INDEX idx_users_state          ON users(state);
CREATE INDEX idx_users_tokens_user    ON users_tokens(id_user);
CREATE INDEX idx_users_tokens_expires ON users_tokens(expires_at);

-- Story Core (all scoped by id_story)
CREATE INDEX idx_stories_category     ON list_stories(category);
CREATE INDEX idx_stories_visibility   ON list_stories(visibility);
CREATE INDEX idx_stories_diff_story   ON list_stories_difficulty(id_story);
CREATE INDEX idx_keys_story           ON list_keys(id_story);
CREATE INDEX idx_keys_name            ON list_keys(id_story, name);
CREATE INDEX idx_classes_story        ON list_classes(id_story);
CREATE INDEX idx_classes_bonus_class  ON list_classes_bonus(id_class);
CREATE INDEX idx_traits_story         ON list_traits(id_story);
CREATE INDEX idx_char_templates_story ON list_character_templates(id_story);

-- Story Locations & Items
CREATE INDEX idx_locations_story      ON list_locations(id_story);
CREATE INDEX idx_locations_safe       ON list_locations(id_story, is_safe);
CREATE INDEX idx_loc_neighbors_from   ON list_locations_neighbors(id_location_from);
CREATE INDEX idx_loc_neighbors_to     ON list_locations_neighbors(id_location_to);
CREATE INDEX idx_loc_neighbors_story  ON list_locations_neighbors(id_story);
CREATE INDEX idx_items_story          ON list_items(id_story);
CREATE INDEX idx_items_effects_item   ON list_items_effects(id_item);
CREATE INDEX idx_weather_story        ON list_weather_rules(id_story);
CREATE INDEX idx_weather_active       ON list_weather_rules(id_story, active);

-- Story Events & Choices
CREATE INDEX idx_events_story         ON list_events(id_story);
CREATE INDEX idx_events_type          ON list_events(id_story, type);
CREATE INDEX idx_events_location      ON list_events(id_specific_location);
CREATE INDEX idx_events_effects_event ON list_events_effects(id_event);
CREATE INDEX idx_choices_story        ON list_choices(id_story);
CREATE INDEX idx_choices_event        ON list_choices(id_event);
CREATE INDEX idx_choices_location     ON list_choices(id_location);
CREATE INDEX idx_choices_cond_choice  ON list_choices_conditions(id_choices);
CREATE INDEX idx_choices_eff_choice   ON list_choices_effects(id_choices);
CREATE INDEX idx_global_rand_story    ON list_global_random_events(id_story);
CREATE INDEX idx_missions_story       ON list_missions(id_story);
CREATE INDEX idx_missions_steps_miss  ON list_missions_steps(id_mission);

-- Story Content
CREATE INDEX idx_cards_story          ON list_cards(id_story);
CREATE INDEX idx_texts_story_text     ON list_texts(id_story, id_text);
CREATE INDEX idx_texts_lang           ON list_texts(id_story, lang);
CREATE INDEX idx_creator_story        ON list_creator(id_story);

-- Gaming Core
CREATE INDEX idx_match_story          ON gaming_match(id_story);
CREATE INDEX idx_match_status         ON gaming_match(status);
CREATE INDEX idx_match_creator        ON gaming_match(id_user_creator);
CREATE INDEX idx_char_inst_match      ON gaming_character_instance(id_match);
CREATE INDEX idx_char_inst_user       ON gaming_character_instance(id_user);
CREATE INDEX idx_char_inst_location   ON gaming_character_instance(id_location);
CREATE INDEX idx_char_traits_char     ON gaming_character_traits(id_character_match);
CREATE INDEX idx_backpack_char        ON gaming_backpack_resources(id_character_match);
CREATE INDEX idx_inventory_char       ON gaming_inventory_items(id_character_match);
CREATE INDEX idx_inventory_item       ON gaming_inventory_items(id_item);

-- Gaming State
CREATE INDEX idx_state_reg_match      ON gaming_state_registry(id_match);
CREATE INDEX idx_state_reg_key        ON gaming_state_registry(id_match, key);
CREATE INDEX idx_turn_queue_match     ON gaming_turn_queue(id_match);
CREATE INDEX idx_active_effects_match ON gaming_active_effects(id_match);
CREATE INDEX idx_active_effects_char  ON gaming_active_effects(id_character_match);
CREATE INDEX idx_active_choices_match ON gaming_active_choices(id_match);
CREATE INDEX idx_story_progress_match ON gaming_story_progress(id_match);
CREATE INDEX idx_temp_vars_match      ON gaming_temp_variables(id_match);
CREATE INDEX idx_temp_vars_char       ON gaming_temp_variables(id_character_match);

-- Gaming Social
CREATE INDEX idx_trades_match         ON gaming_trades(id_match);
CREATE INDEX idx_trades_status        ON gaming_trades(status);
CREATE INDEX idx_trades_sender        ON gaming_trades(id_character_match_sender);
CREATE INDEX idx_trades_dest          ON gaming_trades(id_character_match_dest);
CREATE INDEX idx_move_invites_match   ON gaming_movement_invites(id_match);
CREATE INDEX idx_move_invites_state   ON gaming_movement_invites(state);
CREATE INDEX idx_notif_queue_match    ON gaming_notification_queue(id_match);
CREATE INDEX idx_user_sessions_user   ON gaming_user_sessions(id_user);
CREATE INDEX idx_user_sessions_match  ON gaming_user_sessions(id_match);
CREATE INDEX idx_user_sessions_online ON gaming_user_sessions(is_online);
CREATE INDEX idx_chat_match           ON chat_messages(id_match);
CREATE INDEX idx_chat_user            ON chat_messages(id_user);

-- Log Tables
CREATE INDEX idx_log_events_match     ON log_events(id_match);
CREATE INDEX idx_log_events_char      ON log_events(id_character_match);
CREATE INDEX idx_log_movements_match  ON log_movements(id_match);
CREATE INDEX idx_log_item_usage_match ON log_item_usage(id_match);
CREATE INDEX idx_log_item_usage_char  ON log_item_usage(id_character_match);
CREATE INDEX idx_log_weather_match    ON log_weather(id_match);
CREATE INDEX idx_log_weather_clock    ON log_weather(id_match, clock);
CREATE INDEX idx_log_clock_match      ON log_clock_history(id_match);
CREATE INDEX idx_log_lock_match       ON log_lock_history(id_match);
CREATE INDEX idx_log_choices_match    ON log_choices_executed(id_match);

-- Snapshot
CREATE INDEX idx_snapshot_match       ON system_snapshot(id_match);
CREATE INDEX idx_snapshot_story       ON system_snapshot(id_story);
CREATE INDEX idx_snapshot_type        ON system_snapshot(type);
