# SonarCloud configuration for Paths Games Python Backend
sonar.projectKey=paths-game-backend-python
sonar.organization=gamespaths
sonar.projectName=Backend Python

sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Python settings
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/__pycache__/**,.venv/**,..pytest_cache,database*
sonar.coverage.exclusions=tests/**
