# SonarCloud configuration for Paths Games PHP Backend
sonar.projectKey=paths-game-backend-php
sonar.organization=gamespaths
sonar.projectName=Backend Php

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# PHP settings
sonar.language=php
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml

# Exclusions
sonar.exclusions=vendor/**,public/index.php
sonar.coverage.exclusions=tests/**
