-- =============================================
-- Paths Games - Database Schema V0.10.9
-- Log / Audit Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: log_events, log_movements, log_item_usage,
--         log_weather, log_clock_history, log_lock_history,
--         log_choices_executed
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: log_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS log_events (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match            INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  INTEGER REFERENCES gaming_character_instance(id),
    timestamp           TEXT    NOT NULL DEFAULT (datetime('now')),
    id_event            INTEGER REFERENCES list_events(id),
    id_choise           INTEGER REFERENCES list_choices(id),
    log_message         TEXT,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS log_movements (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match            INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  INTEGER REFERENCES gaming_character_instance(id),
    id_location_from    INTEGER REFERENCES list_locations(id),
    id_location_to      INTEGER REFERENCES list_locations(id),
    id_event            INTEGER REFERENCES list_events(id),
    id_choise           INTEGER REFERENCES list_choices(id),
    log_message         TEXT,
    energy              INTEGER,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS log_item_usage (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match            INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  INTEGER NOT NULL REFERENCES gaming_character_instance(id),
    id_item             INTEGER NOT NULL REFERENCES list_items(id),
    counter             INTEGER DEFAULT 1,
    effects_json        TEXT,
    timestamp           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS log_weather (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid            TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match        INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    clock           INTEGER NOT NULL,
    id_weather      INTEGER REFERENCES list_weather_rules(id),
    timestamp_start TEXT,
    timestamp_end   TEXT,
    ts_insert       TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update       TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS log_clock_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid            TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match        INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    clock           INTEGER NOT NULL,
    weather         TEXT,
    timestamp_start TEXT,
    timestamp_end   TEXT,
    id_event_start  INTEGER REFERENCES list_events(id),
    id_event_end    INTEGER REFERENCES list_events(id),
    ts_insert       TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update       TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS log_lock_history (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match            INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  INTEGER REFERENCES gaming_character_instance(id),
    lock_start          TEXT    NOT NULL DEFAULT (datetime('now')),
    lock_end            TEXT,
    reason              TEXT,
    message             TEXT,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS log_choices_executed (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid        TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match    INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    clock       INTEGER,
    id_event    INTEGER REFERENCES list_events(id),
    id_choise   INTEGER REFERENCES list_choices(id),
    log_message TEXT,
    ts_insert   TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update   TEXT    NOT NULL DEFAULT (datetime('now'))
);
