-- =============================================
-- Paths Games - Database Schema V0.10.6
-- Gaming Core Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: gaming_match, gaming_character_instance,
--         gaming_character_traits, gaming_backpack_resources,
--         gaming_inventory_items
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: gaming_)
-- =============================================
-- gaming_match.status: CREATED, RUNNING, PAUSED, ENDED, GAMEOVER
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS gaming_match (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                        TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story                    INTEGER NOT NULL REFERENCES list_stories(id),
    name                        TEXT,
    id_difficulty               INTEGER NOT NULL REFERENCES list_stories_difficulty(id),
    exp_cost                    INTEGER NOT NULL DEFAULT 5,
    status                      TEXT    NOT NULL DEFAULT 'CREATED',
    current_clock               INTEGER NOT NULL DEFAULT 0,
    id_current_weather          INTEGER REFERENCES list_weather_rules(id),
    id_user_creator             INTEGER NOT NULL REFERENCES users(id),
    timestamp_start             TEXT,
    timestamp_lock_expiration   TEXT,
    timestamp_gameover          TEXT,
    timestamp_end               TEXT,
    id_character_current_turn   INTEGER,                         -- logical FK to gaming_character_instance(id)
    secure_location_param       INTEGER DEFAULT 0,
    counter_consecutive_pass    INTEGER NOT NULL DEFAULT 0,
    ts_insert                   TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                   TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS gaming_character_instance (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                     TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match                 INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_user                  INTEGER NOT NULL REFERENCES users(id),
    id_character_template    INTEGER NOT NULL REFERENCES list_character_templates(id_tipo),
    dexterity                INTEGER NOT NULL DEFAULT 1,
    intelligence             INTEGER NOT NULL DEFAULT 1,
    constitution             INTEGER NOT NULL DEFAULT 1,
    energy                   INTEGER NOT NULL DEFAULT 0,
    life                     INTEGER NOT NULL DEFAULT 1,
    sad                      INTEGER NOT NULL DEFAULT 0,
    id_location              INTEGER REFERENCES list_locations(id),
    is_sleeping              INTEGER NOT NULL DEFAULT 0,
    is_coma                  INTEGER NOT NULL DEFAULT 0,
    clock_in_coma            INTEGER DEFAULT 0,
    timestamp_last_pass      TEXT,
    counter_consecutive_pass INTEGER NOT NULL DEFAULT 0,
    ts_insert                TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS gaming_character_traits (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_match            INTEGER NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  INTEGER NOT NULL REFERENCES gaming_character_instance(id) ON DELETE CASCADE,
    id_traits           INTEGER NOT NULL REFERENCES list_traits(id),
    id_event            INTEGER REFERENCES list_events(id),
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS gaming_backpack_resources (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_character_match  INTEGER NOT NULL UNIQUE REFERENCES gaming_character_instance(id) ON DELETE CASCADE,
    food                INTEGER NOT NULL DEFAULT 0,
    magic               INTEGER NOT NULL DEFAULT 0,
    coin                INTEGER NOT NULL DEFAULT 0,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS gaming_inventory_items (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_character_match  INTEGER NOT NULL REFERENCES gaming_character_instance(id) ON DELETE CASCADE,
    id_item             INTEGER NOT NULL REFERENCES list_items(id),
    amount              INTEGER NOT NULL DEFAULT 1,
    state               TEXT    DEFAULT 'ACTIVE',
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);
