-- =============================================
-- Paths Games - Database Schema V0.10.0
-- System Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: global_game_version, global_runtime_variables
-- Reference: Step 09 - Design Core Data Model (Section 1.1)
-- Naming:   Step 06 - Naming Conventions (prefix: global_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS global_game_version (
    id          INTEGER PRIMARY KEY,
    uuid        TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    version     TEXT    NOT NULL,
    description TEXT,
    ts_insert   TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update   TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS global_runtime_variables (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid         TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    type         TEXT    NOT NULL,
    key          TEXT    NOT NULL UNIQUE,
    string_value TEXT,
    int_value    INTEGER,
    description  TEXT,
    min_value    INTEGER,
    max_value    INTEGER,
    min_version  TEXT,
    max_version  TEXT,
    ts_insert    TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update    TEXT    NOT NULL DEFAULT (datetime('now'))
);
