-- =============================================
-- Paths Games - Database Schema V0.10.1
-- User Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: users, users_tokens
-- Reference: Step 09 - Design Core Data Model (Section 1.2)
-- Naming:   Step 06 - Naming Conventions (prefix: users)
-- =============================================
-- users.state: 1=registration, 2=active, 3=blocked, 4=banned, 5=password_reset, 6=guest
-- users.role:  ADMIN or PLAYER
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS users (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    username            TEXT    NOT NULL UNIQUE,
    password_hash       TEXT,
    email_address       TEXT,
    google_id_sso       TEXT,
    role                TEXT    NOT NULL DEFAULT 'PLAYER',
    state               INTEGER NOT NULL DEFAULT 1,
    nickname            TEXT,
    language            TEXT    DEFAULT 'en',
    guest_cookie_token  TEXT,
    guest_expires_at    TEXT,
    theme_selected      TEXT    DEFAULT 'default',
    ts_registration     TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_last_access      TEXT,
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS users_tokens (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid          TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_user       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token TEXT    NOT NULL,
    expires_at    TEXT    NOT NULL,
    revoked       INTEGER NOT NULL DEFAULT 0,
    ts_insert     TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update     TEXT    NOT NULL DEFAULT (datetime('now'))
);
