-- =============================================
-- Paths Games - Database Schema V0.10.4
-- Story Events & Choices Tables (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: list_events, list_events_effects, list_choices,
--         list_choices_conditions, list_choices_effects,
--         list_global_random_events, list_missions, list_missions_steps
-- Reference: Step 09 - Design Core Data Model (Section 1.3)
-- Naming:   Step 06 - Naming Conventions (prefix: list_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE IF NOT EXISTS list_events (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                     TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card                  INTEGER,                            -- logical FK to list_cards(id)
    id_story                 INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_specific_location     INTEGER REFERENCES list_locations(id),
    id_text_name             INTEGER,                            -- references list_texts(id_text)
    id_text_description      INTEGER,                            -- references list_texts(id_text)
    type                     TEXT    NOT NULL DEFAULT 'NORMAL',  -- AUTOMATIC, FIRST, NORMAL
    cost_enery               INTEGER DEFAULT 0,                  -- energy cost to trigger
    flag_end_time            INTEGER NOT NULL DEFAULT 0,
    characteristic_to_add    TEXT,
    characteristic_to_remove TEXT,
    key_to_add               TEXT,
    key_value_to_add         TEXT,
    id_item_to_add           INTEGER REFERENCES list_items(id),
    id_weather               INTEGER REFERENCES list_weather_rules(id),
    id_event_next            INTEGER REFERENCES list_events(id),
    coin_cost                INTEGER DEFAULT 0,
    ts_insert                TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update                TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS list_events_effects (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid             TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card          INTEGER,                                    -- logical FK to list_cards(id)
    id_story         INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_event         INTEGER NOT NULL REFERENCES list_events(id) ON DELETE CASCADE,
    statistics       TEXT,                                       -- life, energy, exp, sad, dex, int, cos, food, magic, coin
    value            INTEGER DEFAULT 0,
    target           TEXT    DEFAULT 'ALL',                      -- ALL or ONLY_ONE
    traits_to_add    TEXT,
    traits_to_remove TEXT,
    target_class     INTEGER REFERENCES list_classes(id),
    id_item_target   INTEGER REFERENCES list_items(id),
    item_action      TEXT,                                       -- REMOVE or ADD
    ts_insert        TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update        TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS list_choices (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card             INTEGER,                                 -- logical FK to list_cards(id)
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_event            INTEGER REFERENCES list_events(id),
    id_location         INTEGER REFERENCES list_locations(id),
    priority            INTEGER DEFAULT 0,
    id_text_name        INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    id_text_narrative   INTEGER,                                 -- references list_texts(id_text)
    id_event_torun      INTEGER REFERENCES list_events(id),
    limit_sad           INTEGER,
    limit_dex           INTEGER,
    limit_int           INTEGER,
    limit_cos           INTEGER,
    otherwise_flag      INTEGER NOT NULL DEFAULT 0,
    is_progress         INTEGER NOT NULL DEFAULT 0,
    logic_operator      TEXT    DEFAULT 'AND',                   -- AND or OR
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS list_choices_conditions (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story            INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_choices          INTEGER NOT NULL REFERENCES list_choices(id) ON DELETE CASCADE,
    type                TEXT    NOT NULL,                         -- KEYS, ITEM, CLASS, LOCATION, ALL_IN_SAME_LOC, traits, statistics, statistics_SUM
    key                 TEXT,
    value               TEXT,
    operator            TEXT    DEFAULT '=',                      -- =, >, <, !=
    id_text_name        INTEGER,                                 -- references list_texts(id_text)
    id_text_description INTEGER,                                 -- references list_texts(id_text)
    ts_insert           TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update           TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS list_choices_effects (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid            TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_story        INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_choices      INTEGER NOT NULL REFERENCES list_choices(id) ON DELETE CASCADE,
    id_scelta       INTEGER,
    flag_group      INTEGER NOT NULL DEFAULT 0,
    statistics      TEXT,                                        -- life, energy, sad, DEX, COS, INT
    value           INTEGER DEFAULT 0,
    id_text         INTEGER,                                     -- references list_texts(id_text)
    key             TEXT,
    value_to_add    TEXT,
    value_to_remove TEXT,
    ts_insert       TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update       TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS list_global_random_events (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid            TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card         INTEGER,                                     -- logical FK to list_cards(id)
    id_story        INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    condition_key   TEXT,
    condition_value TEXT,
    probability     INTEGER NOT NULL DEFAULT 0,
    id_text         INTEGER,                                     -- references list_texts(id_text)
    id_event        INTEGER REFERENCES list_events(id),
    ts_insert       TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update       TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS list_missions (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                 TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card              INTEGER,                                -- logical FK to list_cards(id)
    id_story             INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    condition_key        TEXT,
    condition_value_from TEXT,
    condition_value_to   TEXT,
    id_text_name         INTEGER,                                -- references list_texts(id_text)
    id_text_description  INTEGER,                                -- references list_texts(id_text)
    id_event_completed   INTEGER REFERENCES list_events(id),
    ts_insert            TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update            TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS list_missions_steps (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                 TEXT    NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',1+abs(random())%4,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))),
    id_card              INTEGER,                                -- logical FK to list_cards(id)
    id_story             INTEGER NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_mission           INTEGER NOT NULL REFERENCES list_missions(id) ON DELETE CASCADE,
    step                 INTEGER NOT NULL,
    condition_key        TEXT,
    condition_value_from TEXT,
    condition_value_to   TEXT,
    id_text_name         INTEGER,                                -- references list_texts(id_text)
    id_text_description  INTEGER,                                -- references list_texts(id_text)
    id_event_completed   INTEGER REFERENCES list_events(id),
    ts_insert            TEXT    NOT NULL DEFAULT (datetime('now')),
    ts_update            TEXT    NOT NULL DEFAULT (datetime('now'))
);
