package games.paths.core.port.dev;

import games.paths.core.model.dev.CleanupResult;

/**
 * TestDataCleanupPort - Inbound port for the dev-only test-data cleanup use case.
 *
 * <p>Part of the Hexagonal Architecture: the adapter-rest module calls this port
 * to remove the rows generated by automated (Robot Framework) test runs.</p>
 *
 * <p>Test rows are identified by the canonical {@code robottest} marker carried
 * on the guest username and the match name. Every other row is preserved.</p>
 */
public interface TestDataCleanupPort {

    /**
     * Deletes every guest and match created by automated test runs.
     *
     * @return a {@link CleanupResult} with the number of guests and matches removed
     */
    CleanupResult cleanupTestData();
}
