spring:
  application:
    name: paths-game-backend
  profiles:
    active: dev

game:
  server:
    version: 0.11.1
    # manually change this version if needed >0.11.1 
  database:
    # Configurable SQLite path — override with -Dgame.database.path=/your/path
    path: ${user.home}/.paths.games/database.sqlite
