-- =============================================
-- Paths Games - Database Schema V0.10.0
-- System Tables (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: global_game_version, global_runtime_variables
-- Reference: Step 09 - Design Core Data Model (Section 1.1)
-- Naming:   Step 06 - Naming Conventions (prefix: global_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================



CREATE TABLE global_game_version (
    id          INTEGER      PRIMARY KEY,
    uuid        UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    version     VARCHAR(20)  NOT NULL,
    description TEXT,
    ts_insert   TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update   TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE global_runtime_variables (
    id           BIGSERIAL    PRIMARY KEY,
    uuid         UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    type         VARCHAR(50)  NOT NULL,
    key          VARCHAR(100) NOT NULL UNIQUE,
    string_value VARCHAR(500),
    int_value    INTEGER,
    description  TEXT,
    min_value    INTEGER,
    max_value    INTEGER,
    min_version  VARCHAR(20),
    max_version  VARCHAR(20),
    ts_insert    TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update    TIMESTAMP    NOT NULL DEFAULT NOW()
);
