-- =============================================
-- Paths Games - Database Schema V0.10.1
-- User Tables (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: users, users_tokens
-- Reference: Step 09 - Design Core Data Model (Section 1.2)
-- Naming:   Step 06 - Naming Conventions (prefix: users)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE users (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    username            VARCHAR(100) NOT NULL UNIQUE,
    password_hash       VARCHAR(255),
    email_address       VARCHAR(255),
    google_id_sso       VARCHAR(255),
    role                VARCHAR(20)  NOT NULL DEFAULT 'PLAYER',
    state               INTEGER      NOT NULL DEFAULT 1,
    nickname            VARCHAR(100),
    language            VARCHAR(10)  DEFAULT 'en',
    guest_cookie_token  VARCHAR(255),
    guest_expires_at    VARCHAR(50),
    theme_selected      VARCHAR(50)  DEFAULT 'default',
    ts_registration     VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_last_access      VARCHAR(50),
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

COMMENT ON COLUMN users.state IS '1=registration, 2=active, 3=blocked, 4=banned, 5=password_reset, 6=guest';
COMMENT ON COLUMN users.role IS 'ADMIN or PLAYER';

CREATE TABLE users_tokens (
    id            BIGSERIAL    PRIMARY KEY,
    uuid          VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_user       BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token VARCHAR(500) NOT NULL,
    expires_at    VARCHAR(50)    NOT NULL,
    revoked       BOOLEAN      NOT NULL DEFAULT FALSE,
    ts_insert     VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update     VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);
