-- =============================================
-- Paths Games - Database Schema V0.10.8
-- Gaming Social Tables (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: gaming_trades, gaming_movement_invites,
--         gaming_notification_queue, gaming_user_sessions,
--         chat_messages
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: gaming_, chat_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE gaming_trades (
    id                          BIGSERIAL    PRIMARY KEY,
    uuid                        UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    id_match                    BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match_sender   BIGINT       NOT NULL REFERENCES gaming_character_instance(id),
    id_character_match_dest     BIGINT       NOT NULL REFERENCES gaming_character_instance(id),
    id_item                     BIGINT       REFERENCES list_items(id),
    id_inventory_items          BIGINT       REFERENCES gaming_inventory_items(id),
    status                      VARCHAR(30)  NOT NULL DEFAULT 'PENDING_VALIDATION',
    timeout                     TIMESTAMP,
    resource                    VARCHAR(50),
    amount                      INTEGER      DEFAULT 0,
    ts_insert                   TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update                   TIMESTAMP    NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN gaming_trades.status IS 'PENDING_VALIDATION, ACCEPTED, REFUSED, FAILED_INVALID, EXPIRED';
COMMENT ON COLUMN gaming_trades.resource IS 'food, magic, coin';

CREATE TABLE gaming_movement_invites (
    id                          BIGSERIAL    PRIMARY KEY,
    uuid                        UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    id_match                    BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match_sender   BIGINT       NOT NULL REFERENCES gaming_character_instance(id),
    id_character_match_friend   BIGINT       NOT NULL REFERENCES gaming_character_instance(id),
    state                       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    timestamp_send              TIMESTAMP    NOT NULL DEFAULT NOW(),
    timestamp_timeout           TIMESTAMP,
    timestamp_answer            TIMESTAMP,
    energy_cost                 INTEGER      DEFAULT 0,
    ts_insert                   TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update                   TIMESTAMP    NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN gaming_movement_invites.state IS 'PENDING, ACCEPTED, EXPIRED, CANCELLED';

CREATE TABLE gaming_notification_queue (
    id               BIGSERIAL    PRIMARY KEY,
    uuid             UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    id_match         BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_chat          BIGINT,
    flag_system_push BOOLEAN      NOT NULL DEFAULT FALSE,
    timestamp        TIMESTAMP    NOT NULL DEFAULT NOW(),
    type             VARCHAR(50),
    priority         INTEGER      DEFAULT 0,
    ts_insert        TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update        TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE gaming_user_sessions (
    id        BIGSERIAL    PRIMARY KEY,
    uuid      UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    id_user   BIGINT       NOT NULL REFERENCES users(id),
    id_match  BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    last_seen TIMESTAMP    DEFAULT NOW(),
    is_online BOOLEAN      NOT NULL DEFAULT FALSE,
    client_id VARCHAR(255),
    ip        VARCHAR(45),
    device    VARCHAR(100),
    channel   VARCHAR(100),
    ts_insert TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE chat_messages (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    id_match            BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_user             BIGINT       NOT NULL REFERENCES users(id),
    id_character_match  BIGINT       REFERENCES gaming_character_instance(id),
    message             TEXT         NOT NULL,
    timestamp           TIMESTAMP    NOT NULL DEFAULT NOW(),
    counter             INTEGER      DEFAULT 0,
    ts_insert           TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_update           TIMESTAMP    NOT NULL DEFAULT NOW()
);
