-- =============================================
-- Paths Games - Database Schema V0.10.6
-- Gaming Core Tables (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: gaming_match, gaming_character_instance,
--         gaming_character_traits, gaming_backpack_resources,
--         gaming_inventory_items
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: gaming_)
-- =============================================
-- Note: gaming_match.id_character_current_turn references
--       gaming_character_instance(id) which is created after.
--       That FK is deferred to V0.10.11.
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE gaming_match (
    id                          BIGSERIAL    PRIMARY KEY,
    uuid                        VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_story                    BIGINT       NOT NULL REFERENCES list_stories(id),
    name                        VARCHAR(255),
    id_difficulty               BIGINT       NOT NULL REFERENCES list_stories_difficulty(id),
    exp_cost                    INTEGER      NOT NULL DEFAULT 5,
    status                      VARCHAR(20)  NOT NULL DEFAULT 'CREATED',
    current_clock               INTEGER      NOT NULL DEFAULT 0,
    id_current_weather          BIGINT       REFERENCES list_weather_rules(id),
    id_user_creator             BIGINT       NOT NULL REFERENCES users(id),
    timestamp_start             TIMESTAMP,
    timestamp_lock_expiration   TIMESTAMP,
    timestamp_gameover          TIMESTAMP,
    timestamp_end               TIMESTAMP,
    id_character_current_turn   BIGINT,                          -- FK to gaming_character_instance(id), deferred to V0.10.11
    secure_location_param       INTEGER      DEFAULT 0,
    counter_consecutive_pass    INTEGER      NOT NULL DEFAULT 0,
    ts_insert                   VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update                   VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

COMMENT ON COLUMN gaming_match.status IS 'CREATED, RUNNING, PAUSED, ENDED, GAMEOVER';

CREATE TABLE gaming_character_instance (
    id                       BIGSERIAL    PRIMARY KEY,
    uuid                     VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match                 BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_user                  BIGINT       NOT NULL REFERENCES users(id),
    id_character_template    BIGINT       NOT NULL REFERENCES list_character_templates(id_tipo),
    dexterity                INTEGER      NOT NULL DEFAULT 1,
    intelligence             INTEGER      NOT NULL DEFAULT 1,
    constitution             INTEGER      NOT NULL DEFAULT 1,
    energy                   INTEGER      NOT NULL DEFAULT 0,
    life                     INTEGER      NOT NULL DEFAULT 1,
    sad                      INTEGER      NOT NULL DEFAULT 0,
    id_location              BIGINT       REFERENCES list_locations(id),
    is_sleeping              BOOLEAN      NOT NULL DEFAULT FALSE,
    is_coma                  BOOLEAN      NOT NULL DEFAULT FALSE,
    clock_in_coma            INTEGER      DEFAULT 0,
    timestamp_last_pass      TIMESTAMP,
    counter_consecutive_pass INTEGER      NOT NULL DEFAULT 0,
    ts_insert                VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update                VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE gaming_character_traits (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match            BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  BIGINT       NOT NULL REFERENCES gaming_character_instance(id) ON DELETE CASCADE,
    id_traits           BIGINT       NOT NULL REFERENCES list_traits(id),
    id_event            BIGINT       REFERENCES list_events(id),
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE gaming_backpack_resources (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_character_match  BIGINT       NOT NULL UNIQUE REFERENCES gaming_character_instance(id) ON DELETE CASCADE,
    food                INTEGER      NOT NULL DEFAULT 0,
    magic               INTEGER      NOT NULL DEFAULT 0,
    coin                INTEGER      NOT NULL DEFAULT 0,
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE gaming_inventory_items (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_character_match  BIGINT       NOT NULL REFERENCES gaming_character_instance(id) ON DELETE CASCADE,
    id_item             BIGINT       NOT NULL REFERENCES list_items(id),
    amount              INTEGER      NOT NULL DEFAULT 1,
    state               VARCHAR(30)  DEFAULT 'ACTIVE',
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);
