-- =============================================
-- Paths Games - Database Schema V0.10.10
-- Snapshot Table (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: system_snapshot
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: system_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================


CREATE TABLE system_snapshot (
    id          BIGSERIAL    PRIMARY KEY,
    uuid        VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_story    BIGINT       NOT NULL REFERENCES list_stories(id),
    id_match    BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    timestamp   TIMESTAMP    NOT NULL DEFAULT NOW(),
    type        VARCHAR(20)  NOT NULL DEFAULT 'FULL',
    jsonb_data  JSONB,
    file_path   TEXT,
    description TEXT,
    ts_insert   VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update   VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

COMMENT ON COLUMN system_snapshot.type IS 'FULL or LIGHT';
