-- =============================================
-- Paths Games - Database Schema V0.10.4
-- Story Events & Choices Tables (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: list_events, list_events_effects, list_choices,
--         list_choices_conditions, list_choices_effects,
--         list_global_random_events, list_missions, list_missions_steps
-- Reference: Step 09 - Design Core Data Model (Section 1.3)
-- Naming:   Step 06 - Naming Conventions (prefix: list_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE list_events (
    id                       BIGSERIAL,
    uuid                     VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card                  BIGINT,                              -- FK to list_cards(id), deferred
    id_story                 BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_specific_location     BIGINT,
    id_text_name             BIGINT,                              -- references list_texts(id_text)
    id_text_description      BIGINT,                              -- references list_texts(id_text)
    type                     VARCHAR(30)  NOT NULL DEFAULT 'NORMAL',
    cost_enery               INTEGER      DEFAULT 0,
    flag_end_time            INTEGER      NOT NULL DEFAULT 0,
    characteristic_to_add    VARCHAR(200),
    characteristic_to_remove VARCHAR(200),
    key_to_add               VARCHAR(200),
    key_value_to_add         VARCHAR(500),
    id_item_to_add           BIGINT,
    id_weather               BIGINT,
    id_event_next            BIGINT,
    coin_cost                INTEGER      DEFAULT 0,
    ts_insert                VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update                VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_specific_location, id_story) REFERENCES list_locations(id, id_story),
    FOREIGN KEY (id_item_to_add, id_story) REFERENCES list_items(id, id_story),
    FOREIGN KEY (id_weather, id_story) REFERENCES list_weather_rules(id, id_story),
    FOREIGN KEY (id_event_next, id_story) REFERENCES list_events(id, id_story)
);

COMMENT ON COLUMN list_events.type IS 'AUTOMATIC, FIRST, NORMAL';
COMMENT ON COLUMN list_events.cost_enery IS 'Energy cost to trigger this event';

CREATE TABLE list_events_effects (
    id               BIGSERIAL,
    uuid             VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card          BIGINT,                                      -- FK to list_cards(id), deferred
    id_story         BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_event         BIGINT       NOT NULL,
    statistics       VARCHAR(50),
    value            INTEGER      DEFAULT 0,
    target           VARCHAR(20)  DEFAULT 'ALL',
    traits_to_add    VARCHAR(200),
    traits_to_remove VARCHAR(200),
    target_class     BIGINT,
    id_item_target   BIGINT,
    item_action      VARCHAR(20),
    ts_insert        VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update        VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_event, id_story) REFERENCES list_events(id, id_story) ON DELETE CASCADE,
    FOREIGN KEY (target_class, id_story) REFERENCES list_classes(id, id_story),
    FOREIGN KEY (id_item_target, id_story) REFERENCES list_items(id, id_story)
);

COMMENT ON COLUMN list_events_effects.target IS 'ALL or ONLY_ONE';
COMMENT ON COLUMN list_events_effects.item_action IS 'REMOVE or ADD';
COMMENT ON COLUMN list_events_effects.statistics IS 'life, energy, exp, sad, dex, int, cos, food, magic, coin';

CREATE TABLE list_choices (
    id                  BIGSERIAL,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card             BIGINT,                                  -- FK to list_cards(id), deferred
    id_story            BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_event            BIGINT,
    id_location         BIGINT,
    priority            INTEGER      DEFAULT 0,
    id_text_name        BIGINT,                                  -- references list_texts(id_text)
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    id_text_narrative   BIGINT,                                  -- references list_texts(id_text)
    id_event_torun      BIGINT,
    limit_sad           INTEGER,
    limit_dex           INTEGER,
    limit_int           INTEGER,
    limit_cos           INTEGER,
    otherwise_flag      INTEGER      NOT NULL DEFAULT 0,
    is_progress         INTEGER      NOT NULL DEFAULT 0,
    logic_operator      VARCHAR(5)   DEFAULT 'AND',
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_event, id_story) REFERENCES list_events(id, id_story),
    FOREIGN KEY (id_location, id_story) REFERENCES list_locations(id, id_story),
    FOREIGN KEY (id_event_torun, id_story) REFERENCES list_events(id, id_story)
);

COMMENT ON COLUMN list_choices.logic_operator IS 'AND or OR';

CREATE TABLE list_choices_conditions (
    id                  BIGSERIAL,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_story            BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_choices          BIGINT       NOT NULL,
    type                VARCHAR(50)  NOT NULL,
    key                 VARCHAR(200),
    value               VARCHAR(500),
    operator            VARCHAR(10)  DEFAULT '=',
    id_text_name        BIGINT,                                  -- references list_texts(id_text)
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_choices, id_story) REFERENCES list_choices(id, id_story) ON DELETE CASCADE
);

COMMENT ON COLUMN list_choices_conditions.type IS 'KEYS, ITEM, CLASS, LOCATION, ALL_IN_SAME_LOC, traits, statistics, statistics_SUM';
COMMENT ON COLUMN list_choices_conditions.operator IS '=, >, <, !=';

CREATE TABLE list_choices_effects (
    id              BIGSERIAL,
    uuid            VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_story        BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_choices      BIGINT       NOT NULL,
    id_scelta       BIGINT,
    flag_group      INTEGER      NOT NULL DEFAULT 0,
    statistics      VARCHAR(50),
    value           INTEGER      DEFAULT 0,
    id_text         BIGINT,                                      -- references list_texts(id_text)
    key             VARCHAR(200),
    value_to_add    VARCHAR(500),
    value_to_remove VARCHAR(500),
    ts_insert       VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update       VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_choices, id_story) REFERENCES list_choices(id, id_story) ON DELETE CASCADE
);

COMMENT ON COLUMN list_choices_effects.statistics IS 'life, energy, sad, DEX, COS, INT';

CREATE TABLE list_global_random_events (
    id              BIGSERIAL,
    uuid            VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card         BIGINT,                                      -- FK to list_cards(id), deferred
    id_story        BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    condition_key   VARCHAR(200),
    condition_value VARCHAR(500),
    probability     INTEGER      NOT NULL DEFAULT 0,
    id_text         BIGINT,                                      -- references list_texts(id_text)
    id_event        BIGINT,
    ts_insert       VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update       VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_event, id_story) REFERENCES list_events(id, id_story)
);

CREATE TABLE list_missions (
    id                  BIGSERIAL,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card             BIGINT,                                  -- FK to list_cards(id), deferred
    id_story            BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    condition_key       VARCHAR(200),
    condition_value_from VARCHAR(500),
    condition_value_to  VARCHAR(500),
    id_text_name        BIGINT,                                  -- references list_texts(id_text)
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    id_event_completed  BIGINT,
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_event_completed, id_story) REFERENCES list_events(id, id_story)
);

CREATE TABLE list_missions_steps (
    id                   BIGSERIAL,
    uuid                 VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card              BIGINT,                                 -- FK to list_cards(id), deferred
    id_story             BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_mission           BIGINT       NOT NULL,
    step                 INTEGER      NOT NULL,
    condition_key        VARCHAR(200),
    condition_value_from VARCHAR(500),
    condition_value_to   VARCHAR(500),
    id_text_name         BIGINT,                                 -- references list_texts(id_text)
    id_text_description  BIGINT,                                 -- references list_texts(id_text)
    id_event_completed   BIGINT,
    ts_insert            VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update            VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_mission, id_story) REFERENCES list_missions(id, id_story) ON DELETE CASCADE,
    FOREIGN KEY (id_event_completed, id_story) REFERENCES list_events(id, id_story)
);
