-- =============================================
-- Paths Games - Database Schema V0.10.12
-- Production Seed Data (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- This file inserts production-required initial data:
--   - Game version record
--   - Runtime configuration variables
-- Reference: Step 09 - Design Core Data Model
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================


-- =============================================
-- Game Version
-- =============================================
INSERT INTO global_game_version (id, version, description)
VALUES (1, 'v0.10.12', 'Initial DB schema creation — Step 0.10');

-- =============================================
-- Runtime Variables — System
-- =============================================
INSERT INTO global_runtime_variables (type, key, string_value, description)
VALUES ('STRING', 'SystemStatus', 'ONLINE', 'Global system status: ONLINE, MAINTENANCE, OFFLINE');

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'MaxActiveMatches', 100, 'Maximum number of concurrent active matches', 1, 1000);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'MaxActiveMatchesGuesses', 10, 'Maximum number of concurrent active matches for guesses', 1, 1000);

-- =============================================
-- Runtime Variables — Timeouts (values in seconds)
-- =============================================
INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'TimeoutPlayerPass', 60, 'Base timeout in seconds before a turn is auto-passed', 10, 600);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'TimeoutPlayerPassPerVolta', 15, 'Additional seconds added per consecutive pass', 0, 120);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'TimeoutTradesExpire', 120, 'Seconds before a pending trade proposal expires', 30, 600);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'TimeoutMovementFollow', 30, 'Seconds to accept a group movement invitation', 10, 300);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'TimeoutChoice', 45, 'Seconds before an active choice auto-selects the otherwise option', 10, 300);

-- =============================================
-- Runtime Variables — WebSocket
-- =============================================
INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'WebSocketHeartbeatInterval', 30, 'WebSocket heartbeat interval in seconds', 5, 120);

-- =============================================
-- Runtime Variables — Game Mechanics
-- =============================================
INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'DefaultInventoryCapacity', 5, 'Base inventory capacity added to constitution + difficulty max_weight', 0, 50);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'TimeBetweenMessages', 5, 'Minimum seconds between chat messages (rate limiting)', 1, 60);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'MaxConsecutivePassBeforeGameover', 20, 'Max consecutive global passes before match ends as GAMEOVER', 5, 100);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'SnapshotRetentionDays', 30, 'Number of days to retain automatic snapshots', 1, 365);

-- =============================================
-- Runtime Variables — User Session
-- =============================================
INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'AFKCleanupTimeout', 300, 'Seconds of inactivity before a user session is marked offline', 60, 1800);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'JWTAccessTokenExpiry', 900, 'JWT access token expiry in seconds (15 minutes)', 60, 7200);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'JWTRefreshTokenExpiry', 604800, 'JWT refresh token expiry in seconds (7 days)', 3600, 2592000);

INSERT INTO global_runtime_variables (type, key, int_value, description, min_value, max_value)
VALUES ('INTEGER', 'GuestSessionExpiry', 86400, 'Guest session cookie expiry in seconds (24 hours)', 3600, 604800);

INSERT INTO global_runtime_variables (type, key, string_value, description)
VALUES ('STRING', 'JWTAccessToken', 'The#42!sTheAnswer2All', 'JWT access token' );

