-- =============================================
-- Paths Games - Database Schema V0.10.9
-- Log / Audit Tables (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: log_events, log_movements, log_item_usage,
--         log_weather, log_clock_history, log_lock_history,
--         log_choices_executed
-- Reference: Step 09 - Design Core Data Model (Section 1.4)
-- Naming:   Step 06 - Naming Conventions (prefix: log_)
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================


CREATE TABLE log_events (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match            BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  BIGINT       REFERENCES gaming_character_instance(id),
    timestamp           TIMESTAMP    NOT NULL DEFAULT NOW(),
    id_event            BIGINT       REFERENCES list_events(id),
    id_choise           BIGINT       REFERENCES list_choices(id),
    log_message         TEXT,
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE log_movements (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match            BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  BIGINT       REFERENCES gaming_character_instance(id),
    id_location_from    BIGINT       REFERENCES list_locations(id),
    id_location_to      BIGINT       REFERENCES list_locations(id),
    id_event            BIGINT       REFERENCES list_events(id),
    id_choise           BIGINT       REFERENCES list_choices(id),
    log_message         TEXT,
    energy              INTEGER,
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE log_item_usage (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match            BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  BIGINT       NOT NULL REFERENCES gaming_character_instance(id),
    id_item             BIGINT       NOT NULL REFERENCES list_items(id),
    counter             INTEGER      DEFAULT 1,
    effects_json        JSONB,
    timestamp           TIMESTAMP    NOT NULL DEFAULT NOW(),
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE log_weather (
    id              BIGSERIAL    PRIMARY KEY,
    uuid            VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match        BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    clock           INTEGER      NOT NULL,
    id_weather      BIGINT       REFERENCES list_weather_rules(id),
    timestamp_start TIMESTAMP,
    timestamp_end   TIMESTAMP,
    ts_insert       VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update       VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE log_clock_history (
    id              BIGSERIAL    PRIMARY KEY,
    uuid            VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match        BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    clock           INTEGER      NOT NULL,
    weather         VARCHAR(100),
    timestamp_start TIMESTAMP,
    timestamp_end   TIMESTAMP,
    id_event_start  BIGINT       REFERENCES list_events(id),
    id_event_end    BIGINT       REFERENCES list_events(id),
    ts_insert       VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update       VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE log_lock_history (
    id                  BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match            BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    id_character_match  BIGINT       REFERENCES gaming_character_instance(id),
    lock_start          TIMESTAMP    NOT NULL DEFAULT NOW(),
    lock_end            TIMESTAMP,
    reason              VARCHAR(200),
    message             TEXT,
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE log_choices_executed (
    id          BIGSERIAL    PRIMARY KEY,
    uuid        VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_match    BIGINT       NOT NULL REFERENCES gaming_match(id) ON DELETE CASCADE,
    clock       INTEGER,
    id_event    BIGINT       REFERENCES list_events(id),
    id_choise   BIGINT       REFERENCES list_choices(id),
    log_message TEXT,
    ts_insert   VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update   VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);
