-- =============================================
-- Paths Games - Database Schema V0.10.2
-- Story Core Tables (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Tables: list_stories, list_stories_difficulty, list_keys,
--         list_classes, list_classes_bonus, list_traits,
--         list_character_templates
-- Reference: Step 09 - Design Core Data Model (Section 1.3)
-- Naming:   Step 06 - Naming Conventions (prefix: list_)
-- =============================================
-- Note: list_stories has forward-reference columns to tables created
--       in later migrations (list_cards, list_locations, list_events,
--       list_creator). Those FK constraints are deferred to V0.10.11.
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

CREATE TABLE list_stories (
    id                          BIGSERIAL    PRIMARY KEY,
    uuid                        VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card                     BIGINT,                          -- FK to list_cards(id), deferred to V0.10.11
    id_text_title               BIGINT,                          -- references list_texts(id_text)
    id_text_description         BIGINT,                          -- references list_texts(id_text)
    author                      VARCHAR(255),
    version_min                 VARCHAR(20),
    version_max                 VARCHAR(20),
    id_location_start           BIGINT,                          -- FK to list_locations(id), deferred to V0.10.11
    id_image                    BIGINT,
    id_location_all_player_coma BIGINT,                          -- FK to list_locations(id), deferred to V0.10.11
    id_event_all_player_coma    BIGINT,                          -- FK to list_events(id), deferred to V0.10.11
    id_text_clock_singular      INTEGER DEFAULT 10,
    id_text_clock_plural        INTEGER DEFAULT 11,
    id_event_end_game           BIGINT,                          -- FK to list_events(id), deferred to V0.10.11
    id_text_copyright           BIGINT,                          -- references list_texts(id_text)
    link_copyright              TEXT,
    id_creator                  BIGINT,                          -- FK to list_creator(id), deferred to V0.10.11
    category                    VARCHAR(100),
    "group"                     VARCHAR(100),
    visibility                  VARCHAR(50)  DEFAULT 'PUBLIC',
    priority                    INTEGER      DEFAULT 0,
    peghi                       INTEGER      DEFAULT 0,
    ts_insert                   VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update                   VARCHAR(50)    NOT NULL DEFAULT NOW()::text
);

CREATE TABLE list_stories_difficulty (
    id                       BIGSERIAL   PRIMARY KEY,
    uuid                     VARCHAR(36)        NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card                  BIGINT,                             -- FK to list_cards(id), deferred
    id_story                 BIGINT      NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_description      BIGINT,                             -- references list_texts(id_text)
    exp_cost                 INTEGER     NOT NULL DEFAULT 5,
    max_weight               INTEGER     NOT NULL DEFAULT 10,
    min_character            INTEGER     NOT NULL DEFAULT 1,
    max_character            INTEGER     NOT NULL DEFAULT 4,
    cost_help_coma           INTEGER     NOT NULL DEFAULT 3,
    cost_max_characteristics INTEGER     NOT NULL DEFAULT 3,
    number_max_free_action   INTEGER     NOT NULL DEFAULT 1,
    ts_insert                VARCHAR(50)   NOT NULL DEFAULT NOW()::text,
    ts_update                VARCHAR(50)   NOT NULL DEFAULT NOW()::text,
    UNIQUE (id, id_story)
);

CREATE TABLE list_keys (
    id                  BIGSERIAL,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card             BIGINT,                                  -- FK to list_cards(id), deferred
    id_story            BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    name                VARCHAR(200) NOT NULL,
    value               VARCHAR(500),
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    "group"             VARCHAR(100),
    priority            INTEGER      DEFAULT 0,
    visibility          VARCHAR(50)  DEFAULT 'PUBLIC',
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story)
);

CREATE TABLE list_classes (
    id                 BIGSERIAL,
    uuid               VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card            BIGINT,                                   -- FK to list_cards(id), deferred
    id_story           BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_name       BIGINT,                                   -- references list_texts(id_text)
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    weight_max         INTEGER      NOT NULL DEFAULT 10,
    dexterity_base     INTEGER      NOT NULL DEFAULT 1,
    intelligence_base  INTEGER      NOT NULL DEFAULT 1,
    constitution_base  INTEGER      NOT NULL DEFAULT 1,
    ts_insert          VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update          VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story)
);

CREATE TABLE list_classes_bonus (
    id                  BIGSERIAL,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card             BIGINT,                                  -- FK to list_cards(id), deferred
    id_story            BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_class            BIGINT       NOT NULL,
    statistic           VARCHAR(50)  NOT NULL,
    value               INTEGER      NOT NULL DEFAULT 0,
    id_text_name        BIGINT,                                  -- references list_texts(id_text)
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_class, id_story) REFERENCES list_classes(id, id_story) ON DELETE CASCADE
);

COMMENT ON COLUMN list_classes_bonus.statistic IS 'energy, life, sad, dex, int, cos, food, magic, coin';

CREATE TABLE list_traits (
    id                  BIGSERIAL,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card             BIGINT,                                  -- FK to list_cards(id), deferred
    id_story            BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_class_permitted  BIGINT,
    id_class_prohibited BIGINT,
    id_text_name        BIGINT,                                  -- references list_texts(id_text)
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    cost_positive       INTEGER      DEFAULT 0,
    cost_negative       INTEGER      DEFAULT 0,
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    PRIMARY KEY (id, id_story),
    FOREIGN KEY (id_class_permitted, id_story) REFERENCES list_classes(id, id_story),
    FOREIGN KEY (id_class_prohibited, id_story) REFERENCES list_classes(id, id_story)
);

CREATE TABLE list_character_templates (
    id_tipo             BIGSERIAL    PRIMARY KEY,
    uuid                VARCHAR(36)         NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    id_card             BIGINT,                                  -- FK to list_cards(id), deferred
    id_story            BIGINT       NOT NULL REFERENCES list_stories(id) ON DELETE CASCADE,
    id_text_name        BIGINT,                                  -- references list_texts(id_text)
    id_text_description BIGINT,                                  -- references list_texts(id_text)
    life_max            INTEGER      NOT NULL DEFAULT 10,
    energy_max          INTEGER      NOT NULL DEFAULT 10,
    sad_max             INTEGER      NOT NULL DEFAULT 10,
    dexterity_start     INTEGER      NOT NULL DEFAULT 1,
    intelligence_start  INTEGER      NOT NULL DEFAULT 1,
    constitution_start  INTEGER      NOT NULL DEFAULT 1,
    ts_insert           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    ts_update           VARCHAR(50)    NOT NULL DEFAULT NOW()::text,
    UNIQUE (id_tipo, id_story)
);
