#!/usr/bin/env bash
# start.sh — Generate nginx.conf with admin IP whitelist, then start the stack.
#
# IPs allowed on /api/admin/**:
#   1. ADMIN_IP_WHITELIST from .env (comma-separated, e.g. "10.0.0.1,192.168.1.5")
#   2. Current machine's public IP (auto-detected)
#
# Usage:
#   ./start.sh            # start in foreground
#   ./start.sh -d         # start detached (background)
#   ./start.sh down       # stop and remove containers
#   ./start.sh build      # rebuild Java image before starting

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Load .env if present ────────────────────────────────────────────────────
if [ -f ".env" ]; then
    # shellcheck disable=SC1091
    set -a; . ".env"; set +a
    echo "[start.sh] Loaded .env"
fi

# ── Handle sub-commands ─────────────────────────────────────────────────────
if [ "${1:-}" = "down" ]; then
    docker compose down
    exit 0
fi
if [ "${1:-}" = "build" ]; then
    docker compose build --no-cache backend
    shift
fi

# ── Detect current public IP ────────────────────────────────────────────────
echo "[start.sh] Detecting current public IP…"
CURRENT_IP="$(curl -sf --max-time 5 https://checkip.amazonaws.com \
    || curl -sf --max-time 5 https://api.ipify.org \
    || echo '')"
if [ -n "$CURRENT_IP" ]; then
    echo "[start.sh] Current public IP: $CURRENT_IP"
else
    echo "[start.sh] WARNING: could not auto-detect public IP — only ADMIN_IP_WHITELIST will be used"
fi

# ── Build allow-list (dedup) ─────────────────────────────────────────────────
BASE_LIST="${ADMIN_IP_WHITELIST:-}"
MERGED=""
if [ -n "$BASE_LIST" ] && [ -n "$CURRENT_IP" ]; then
    MERGED="$BASE_LIST,$CURRENT_IP"
elif [ -n "$CURRENT_IP" ]; then
    MERGED="$CURRENT_IP"
else
    MERGED="$BASE_LIST"
fi

# Convert to unique nginx allow directives (one per line, indented)
if [ -n "$MERGED" ]; then
    ALLOW_DIRECTIVES="$(echo "$MERGED" \
        | tr ',' '\n' \
        | awk 'NF && !seen[$0]++' \
        | sed 's/^/            allow /' \
        | sed 's/$/;/')"
    echo "[start.sh] Admin IP whitelist:"
    echo "$MERGED" | tr ',' '\n' | awk 'NF && !seen[$0]++' | sed 's/^/   /'
else
    echo "[start.sh] WARNING: No IPs configured — admin endpoints open to ALL IPs!"
    ALLOW_DIRECTIVES="            # WARNING: no IP restriction configured"
fi

# ── Generate nginx.conf ──────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/nginx.conf" <<NGINXEOF
# Auto-generated by start.sh — do not edit manually, re-run start.sh instead.
# Admin IPs: $(echo "${MERGED:-<none>}" | tr ',' ' ')

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    upstream backend {
        server backend:8041;
    }

    server {
        listen 80;
        server_name _;

        # ── Admin endpoints: IP whitelist ─────────────────────────────────
        location ~ ^/api/admin/ {
${ALLOW_DIRECTIVES}
            deny all;
            proxy_pass         http://backend;
            proxy_set_header   Host              \$host;
            proxy_set_header   X-Real-IP         \$remote_addr;
            proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto \$scheme;
            proxy_read_timeout 60s;
        }

        # ── All other endpoints: open ─────────────────────────────────────
        location / {
            proxy_pass         http://backend;
            proxy_set_header   Host              \$host;
            proxy_set_header   X-Real-IP         \$remote_addr;
            proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto \$scheme;
            proxy_read_timeout 60s;
        }
    }
}
NGINXEOF

echo "[start.sh] nginx.conf generated ✓"

# ── Start the stack ──────────────────────────────────────────────────────────
echo "[start.sh] Starting stack…"
docker compose up "${@}"
