-- =============================================
-- Paths Games - Repeatable Migration
-- Development & Test Seed Data (PostgreSQL)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- This file is re-executed whenever its content changes.
-- It inserts test data for development and testing purposes.
-- NEVER include this in production deployments.
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================

-- Clean previous test data
DELETE FROM chat_messages       WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_choices_executed WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_lock_history    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_clock_history   WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_weather         WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_item_usage      WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_movements       WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM log_events          WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM system_snapshot     WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_temp_variables    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_story_progress    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_active_choices    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_active_effects    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_turn_queue        WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_state_locations   WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_state_registry    WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_notification_queue WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_user_sessions     WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_movement_invites  WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_trades            WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_inventory_items   WHERE id_character_match IN (SELECT id FROM gaming_character_instance WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000));
DELETE FROM gaming_backpack_resources WHERE id_character_match IN (SELECT id FROM gaming_character_instance WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000));
DELETE FROM gaming_character_traits  WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_character_instance WHERE id_match IN (SELECT id FROM gaming_match WHERE id < 1000);
DELETE FROM gaming_match             WHERE id < 1000;
DELETE FROM users_tokens WHERE id_user IN (SELECT id FROM users WHERE username LIKE 'test_%');
DELETE FROM users WHERE username LIKE 'test_%';

-- =============================================
-- Test Users
-- =============================================
-- Password hash is BCrypt of 'password123'
INSERT INTO users (id, username, password_hash, email_address, role, state, nickname, language)
VALUES (1, 'test_admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'admin@test.local', 'ADMIN', 2, 'TestAdmin', 'en');

INSERT INTO users (id, username, password_hash, email_address, role, state, nickname, language)
VALUES (2, 'test_player1', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'player1@test.local', 'PLAYER', 2, 'Alice', 'en');

INSERT INTO users (id, username, password_hash, email_address, role, state, nickname, language)
VALUES (3, 'test_player2', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'player2@test.local', 'PLAYER', 2, 'Bob', 'en');

INSERT INTO users (id, username, password_hash, email_address, role, state, nickname, language)
VALUES (4, 'test_player3', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'player3@test.local', 'PLAYER', 2, 'Charlie', 'it');

-- Reset sequence after explicit ID inserts
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));
