-- =============================================
-- Paths Games - Database Schema V0.10.11
-- Indexes (SQLite)
-- See documentation_v0/Step10_CreateDBschema.md file for details on the database schema and seed data.
-- =============================================
-- Note: SQLite does not support ALTER TABLE ADD CONSTRAINT.
--       Deferred foreign keys (circular references between
--       list_stories ↔ list_cards/list_locations/list_events/list_creator
--       and gaming_match ↔ gaming_character_instance)
--       are enforced at the application level only.
--       This file contains performance indexes.
-- Reference: Step 09 - Design Core Data Model
-- =============================================
-- (C) Paths Games 2042 - All rights reserved - See https://github.com/gamespaths/pathsgames
-- The software is distributed under the terms of the GNU General Public License v3.0
-- NEVER EDIT THIS FILE MANUALLY - THIS FILE IS GENERATED BY THE MIGRATION TOOL
-- =============================================


-- =============================================
-- Users
-- =============================================
CREATE INDEX IF NOT EXISTS idx_users_email          ON users(email_address);
CREATE INDEX IF NOT EXISTS idx_users_google_sso     ON users(google_id_sso);
CREATE INDEX IF NOT EXISTS idx_users_state          ON users(state);
CREATE INDEX IF NOT EXISTS idx_users_tokens_user    ON users_tokens(id_user);
CREATE INDEX IF NOT EXISTS idx_users_tokens_expires ON users_tokens(expires_at);

-- =============================================
-- Story Core
-- =============================================
CREATE INDEX IF NOT EXISTS idx_stories_category     ON list_stories(category);
CREATE INDEX IF NOT EXISTS idx_stories_visibility   ON list_stories(visibility);
CREATE INDEX IF NOT EXISTS idx_stories_diff_story   ON list_stories_difficulty(id_story);
CREATE INDEX IF NOT EXISTS idx_keys_story           ON list_keys(id_story);
CREATE INDEX IF NOT EXISTS idx_keys_name            ON list_keys(id_story, name);
CREATE INDEX IF NOT EXISTS idx_classes_story        ON list_classes(id_story);
CREATE INDEX IF NOT EXISTS idx_classes_bonus_class  ON list_classes_bonus(id_class);
CREATE INDEX IF NOT EXISTS idx_traits_story         ON list_traits(id_story);
CREATE INDEX IF NOT EXISTS idx_char_templates_story ON list_character_templates(id_story);

-- =============================================
-- Story Locations & Items
-- =============================================
CREATE INDEX IF NOT EXISTS idx_locations_story      ON list_locations(id_story);
CREATE INDEX IF NOT EXISTS idx_locations_safe       ON list_locations(id_story, is_safe);
CREATE INDEX IF NOT EXISTS idx_loc_neighbors_from   ON list_locations_neighbors(id_location_from);
CREATE INDEX IF NOT EXISTS idx_loc_neighbors_to     ON list_locations_neighbors(id_location_to);
CREATE INDEX IF NOT EXISTS idx_loc_neighbors_story  ON list_locations_neighbors(id_story);
CREATE INDEX IF NOT EXISTS idx_items_story          ON list_items(id_story);
CREATE INDEX IF NOT EXISTS idx_items_effects_item   ON list_items_effects(id_item);
CREATE INDEX IF NOT EXISTS idx_weather_story        ON list_weather_rules(id_story);
CREATE INDEX IF NOT EXISTS idx_weather_active       ON list_weather_rules(id_story, active);

-- =============================================
-- Story Events & Choices
-- =============================================
CREATE INDEX IF NOT EXISTS idx_events_story         ON list_events(id_story);
CREATE INDEX IF NOT EXISTS idx_events_type          ON list_events(id_story, type);
CREATE INDEX IF NOT EXISTS idx_events_location      ON list_events(id_specific_location);
CREATE INDEX IF NOT EXISTS idx_events_effects_event ON list_events_effects(id_event);
CREATE INDEX IF NOT EXISTS idx_choices_story        ON list_choices(id_story);
CREATE INDEX IF NOT EXISTS idx_choices_event        ON list_choices(id_event);
CREATE INDEX IF NOT EXISTS idx_choices_location     ON list_choices(id_location);
CREATE INDEX IF NOT EXISTS idx_choices_cond_choice  ON list_choices_conditions(id_choices);
CREATE INDEX IF NOT EXISTS idx_choices_eff_choice   ON list_choices_effects(id_choices);
CREATE INDEX IF NOT EXISTS idx_global_rand_story    ON list_global_random_events(id_story);
CREATE INDEX IF NOT EXISTS idx_missions_story       ON list_missions(id_story);
CREATE INDEX IF NOT EXISTS idx_missions_steps_miss  ON list_missions_steps(id_mission);

-- =============================================
-- Story Content
-- =============================================
CREATE INDEX IF NOT EXISTS idx_cards_story          ON list_cards(id_story);
CREATE INDEX IF NOT EXISTS idx_texts_story_text     ON list_texts(id_story, id_text);
CREATE INDEX IF NOT EXISTS idx_texts_lang           ON list_texts(id_story, lang);
CREATE INDEX IF NOT EXISTS idx_creator_story        ON list_creator(id_story);

-- =============================================
-- Gaming Core
-- =============================================
CREATE INDEX IF NOT EXISTS idx_match_story          ON gaming_match(id_story);
CREATE INDEX IF NOT EXISTS idx_match_status         ON gaming_match(status);
CREATE INDEX IF NOT EXISTS idx_match_creator        ON gaming_match(id_user_creator);
CREATE INDEX IF NOT EXISTS idx_char_inst_match      ON gaming_character_instance(id_match);
CREATE INDEX IF NOT EXISTS idx_char_inst_user       ON gaming_character_instance(id_user);
CREATE INDEX IF NOT EXISTS idx_char_inst_location   ON gaming_character_instance(id_location);
CREATE INDEX IF NOT EXISTS idx_char_traits_char     ON gaming_character_traits(id_character_match);
CREATE INDEX IF NOT EXISTS idx_backpack_char        ON gaming_backpack_resources(id_character_match);
CREATE INDEX IF NOT EXISTS idx_inventory_char       ON gaming_inventory_items(id_character_match);
CREATE INDEX IF NOT EXISTS idx_inventory_item       ON gaming_inventory_items(id_item);

-- =============================================
-- Gaming State
-- =============================================
CREATE INDEX IF NOT EXISTS idx_state_reg_match      ON gaming_state_registry(id_match);
CREATE INDEX IF NOT EXISTS idx_state_reg_key        ON gaming_state_registry(id_match, key);
CREATE INDEX IF NOT EXISTS idx_turn_queue_match     ON gaming_turn_queue(id_match);
CREATE INDEX IF NOT EXISTS idx_active_effects_match ON gaming_active_effects(id_match);
CREATE INDEX IF NOT EXISTS idx_active_effects_char  ON gaming_active_effects(id_character_match);
CREATE INDEX IF NOT EXISTS idx_active_choices_match ON gaming_active_choices(id_match);
CREATE INDEX IF NOT EXISTS idx_story_progress_match ON gaming_story_progress(id_match);
CREATE INDEX IF NOT EXISTS idx_temp_vars_match      ON gaming_temp_variables(id_match);
CREATE INDEX IF NOT EXISTS idx_temp_vars_char       ON gaming_temp_variables(id_character_match);

-- =============================================
-- Gaming Social
-- =============================================
CREATE INDEX IF NOT EXISTS idx_trades_match         ON gaming_trades(id_match);
CREATE INDEX IF NOT EXISTS idx_trades_status        ON gaming_trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_sender        ON gaming_trades(id_character_match_sender);
CREATE INDEX IF NOT EXISTS idx_trades_dest          ON gaming_trades(id_character_match_dest);
CREATE INDEX IF NOT EXISTS idx_move_invites_match   ON gaming_movement_invites(id_match);
CREATE INDEX IF NOT EXISTS idx_move_invites_state   ON gaming_movement_invites(state);
CREATE INDEX IF NOT EXISTS idx_notif_queue_match    ON gaming_notification_queue(id_match);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user   ON gaming_user_sessions(id_user);
CREATE INDEX IF NOT EXISTS idx_user_sessions_match  ON gaming_user_sessions(id_match);
CREATE INDEX IF NOT EXISTS idx_user_sessions_online ON gaming_user_sessions(is_online);
CREATE INDEX IF NOT EXISTS idx_chat_match           ON chat_messages(id_match);
CREATE INDEX IF NOT EXISTS idx_chat_user            ON chat_messages(id_user);

-- =============================================
-- Log Tables
-- =============================================
CREATE INDEX IF NOT EXISTS idx_log_events_match     ON log_events(id_match);
CREATE INDEX IF NOT EXISTS idx_log_events_char      ON log_events(id_character_match);
CREATE INDEX IF NOT EXISTS idx_log_movements_match  ON log_movements(id_match);
CREATE INDEX IF NOT EXISTS idx_log_item_usage_match ON log_item_usage(id_match);
CREATE INDEX IF NOT EXISTS idx_log_item_usage_char  ON log_item_usage(id_character_match);
CREATE INDEX IF NOT EXISTS idx_log_weather_match    ON log_weather(id_match);
CREATE INDEX IF NOT EXISTS idx_log_weather_clock    ON log_weather(id_match, clock);
CREATE INDEX IF NOT EXISTS idx_log_clock_match      ON log_clock_history(id_match);
CREATE INDEX IF NOT EXISTS idx_log_lock_match       ON log_lock_history(id_match);
CREATE INDEX IF NOT EXISTS idx_log_choices_match    ON log_choices_executed(id_match);

-- =============================================
-- Snapshot
-- =============================================
CREATE INDEX IF NOT EXISTS idx_snapshot_match       ON system_snapshot(id_match);
CREATE INDEX IF NOT EXISTS idx_snapshot_story       ON system_snapshot(id_story);
CREATE INDEX IF NOT EXISTS idx_snapshot_type        ON system_snapshot(type);
