import {
  LOCATION_NEIGHBOR_DIRECTION_OPTIONS,
  LOCATION_NEIGHBOR_DIRECTIONS,
  LOCATION_NEIGHBOR_FLAG_BACK_OPTIONS,
} from './locationNeighbors'
import {
  CARD_TYPE_OPTIONS,
  CHOICE_CONDITION_OPERATOR_OPTIONS,
  CHOICE_CONDITION_TYPE_OPTIONS,
  EVENT_EFFECT_TARGET_OPTIONS,
  EVENT_TYPE_OPTIONS,
  EVENT_EFFECT_STATISTICS_OPTIONS,
  ITEM_ACTION_OPTIONS,
  LOGIC_OPERATOR_OPTIONS,
  POSSIBLE_STATISTICS_OPTIONS,
} from './storyFieldOptions'

export const STORIES_ENTITIES_TABS = [
  { id: 'metadata', label: 'Story Info', icon: 'fa-info-circle' },
  { id: 'cards', label: 'Cards', icon: 'fa-id-card' },
  { id: 'creators', label: 'Creators', icon: 'fa-paint-brush' },
  { id: 'texts', label: 'Texts', icon: 'fa-font' },
  { id: 'keys', label: 'Keys', icon: 'fa-key' },
  { id: 'difficulties', label: 'Difficulties', icon: 'fa-layer-group' },
  { id: 'locations', label: 'Locations', icon: 'fa-map-marker-alt' },
  { id: 'location-neighbors', label: 'Loc Neighbors', icon: 'fa-project-diagram' },
  { id: 'events', label: 'Events', icon: 'fa-bolt' },
  { id: 'event-effects', label: 'Event Effects', icon: 'fa-magic' },
  { id: 'items', label: 'Items', icon: 'fa-flask' },
  { id: 'item-effects', label: 'Item Effects', icon: 'fa-cogs' },
  { id: 'character-templates', label: 'Templates', icon: 'fa-user-tag' },
  { id: 'classes', label: 'Classes', icon: 'fa-hat-wizard' },
  { id: 'class-bonuses', label: 'Class Bonuses', icon: 'fa-star-half-alt' },
  { id: 'traits', label: 'Traits', icon: 'fa-star' },
  { id: 'choices', label: 'Choices', icon: 'fa-code-branch' },
  { id: 'choice-conditions', label: 'Choice Cond.', icon: 'fa-filter' },
  { id: 'choice-effects', label: 'Choice Effects', icon: 'fa-random' },
  { id: 'weather-rules', label: 'Weather Rules', icon: 'fa-cloud-sun' },
  { id: 'global-random-events', label: 'Random Events', icon: 'fa-dice' },
  { id: 'missions', label: 'Missions', icon: 'fa-tasks' },
  { id: 'mission-steps', label: 'Mission Steps', icon: 'fa-list-ol' },
]

export const STORIES_ENTITIES_FIELDS = {
    difficulties: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'expCost', label: 'EXP Cost', type: 'number' },
      { key: 'maxWeight', label: 'Max Weight', type: 'number' },
      { key: 'minCharacter', label: 'Min Characters', type: 'number' },
      { key: 'maxCharacter', label: 'Max Characters', type: 'number' },
      { key: 'costHelpComa', label: 'Cost Help Coma', type: 'number' },
      { key: 'costMaxCharacteristics', label: 'Cost Max Characteristics', type: 'number' },
      { key: 'numberMaxFreeAction', label: 'Max Free Actions', type: 'number' },
      // Step 23 — trait cost budgets (empty = no limit)
      { key: 'traitCostPositiveBudget', label: 'Trait Cost Budget (+)', type: 'number' },
      { key: 'traitCostNegativeBudget', label: 'Trait Cost Budget (−)', type: 'number' },
      { key: 'life', label: 'Life', type: 'number' },
      { key: 'energy', label: 'Energy', type: 'number' },
      { key: 'sad', label: 'Sad', type: 'number' },
      { key: 'dexterity', label: 'Dexterity', type: 'number' },
      { key: 'intelligence', label: 'Intelligence', type: 'number' },
      { key: 'constitution', label: 'Constitution', type: 'number' },
      { key: 'weight', label: 'Weight', type: 'number' },
    ],
    locations: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'idTextNarrative', label: 'Narrative Text ID', type: 'number' },
      { key: 'idImage', label: 'Image ID', type: 'number' },
      { key: 'isSafe', label: 'Safe Location', type: 'checkbox' },
      { key: 'costEnergyEnter', label: 'Energy Cost to Enter', type: 'number' },
      { key: 'counterTime', label: 'Counter Time', type: 'number' },
      { key: 'idEventIfCounterZero', label: 'Event if Counter = 0', type: 'number' },
      { key: 'secureParam', label: 'Secure Param', type: 'number' },
      { key: 'idEventIfCharacterStartTime', label: 'Event if Start Time', type: 'number' },
      { key: 'idEventIfCharacterEnterFirstTime', label: 'Event if Enter First', type: 'number' },
      { key: 'idEventIfFirstTime', label: 'Event if First Time', type: 'number' },
      { key: 'idEventNotFirstTime', label: 'Event if Not First Time', type: 'number' },
      { key: 'priorityAutomaticEvent', label: 'Auto Event Priority', type: 'number' },
      { key: 'idAudio', label: 'Audio ID', type: 'number' },
      { key: 'maxCharacters', label: 'Max Characters', type: 'number' },
    ],
    'location-neighbors': [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idLocationFrom', label: 'Location From ID', type: 'number' },
      { key: 'idLocationTo', label: 'Location To ID', type: 'number' },
      { key: 'direction', label: 'Direction', type: 'select', options: LOCATION_NEIGHBOR_DIRECTION_OPTIONS },
      { key: 'conditionRegistryKey', label: 'Condition Registry Key', type: 'text' },
      { key: 'conditionRegistryValue', label: 'Condition Registry Value', type: 'text' },
      { key: 'idTextGo', label: 'Text Go ID', type: 'number' },
      { key: 'idTextBack', label: 'Text Back ID', type: 'number' },
      { key: 'energyCost', label: 'Energy Cost', type: 'number' },
      { key: 'flagBack', label: 'Flag Back', type: 'select', valueType: 'number', options: LOCATION_NEIGHBOR_FLAG_BACK_OPTIONS },
      // Card Back is only meaningful when the neighbor allows going back (flagBack = YES).
      { key: 'idCardBack', label: 'Card Back ID', type: 'number', showIf: (d) => Number(d.flagBack) === 1 },
    ],
    // Step 29 — list_events is the CONDITION side of an event: cost, chain, and the
    // conditions the check procedure evaluates (all of them in AND). Everything the event
    // DOES lives on event-effects below.
    events: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'idSpecificLocation', label: 'Specific Location ID', type: 'number' },
      { key: 'type', label: 'Event Type', type: 'select', options: EVENT_TYPE_OPTIONS },
      { key: 'costEnery', label: 'Energy Cost', type: 'number' },
      { key: 'coinCost', label: 'Coin Cost', type: 'number' },
      { key: 'flagEndTime', label: 'Flag End Time', type: 'number' },
      { key: 'idEventNext', label: 'Next Event ID', type: 'number' },
      // Conditions (AND). idWeather here GATES the event; on an effect it SETS the weather.
      { key: 'idWeather', label: 'Weather (condition)', type: 'number' },
      { key: 'registryKeyCondition', label: 'Registry Key (condition)', type: 'text' },
      { key: 'registryValueCondition', label: 'Registry Value (condition)', type: 'text' },
      { key: 'idItemCondition', label: 'Item Owned (condition)', type: 'number' },
      { key: 'idClassCondition', label: 'Class (condition)', type: 'number' },
    ],
    // Step 29 — the EFFECT side. The card of each row is the narrative the board renders.
    'event-effects': [
      { key: 'idCard', label: 'Card ID (narrative)', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'idEvent', label: 'Event ID', type: 'number' },
      { key: 'statistics', label: 'Statistic', type: 'select', options: EVENT_EFFECT_STATISTICS_OPTIONS },
      { key: 'value', label: 'Value', type: 'number' },
      { key: 'target', label: 'Target', type: 'select', options: EVENT_EFFECT_TARGET_OPTIONS },
      { key: 'targetClass', label: 'Target Class', type: 'number' },
      { key: 'traitsToAdd', label: 'Traits to Add (csv of ids)', type: 'text' },
      { key: 'traitsToRemove', label: 'Traits to Remove (csv of ids)', type: 'text' },
      { key: 'idItemTarget', label: 'Item Target ID', type: 'number' },
      { key: 'itemAction', label: 'Item Action', type: 'select', options: ITEM_ACTION_OPTIONS },
      { key: 'keyToAdd', label: 'Registry Key to Write', type: 'text' },
      { key: 'keyValueToAdd', label: 'Registry Value to Write', type: 'text' },
      { key: 'characteristicToAdd', label: 'Characteristic to Add', type: 'text' },
      { key: 'characteristicToRemove', label: 'Characteristic to Remove', type: 'text' },
      { key: 'idWeather', label: 'Weather to Set (effect)', type: 'number' },
      // v0.29.3 — forced movement: recipients are moved there, no Step 28 checks, no energy.
      { key: 'idLocation', label: 'Move To Location ID (effect)', type: 'number' },
    ],
    items: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'weight', label: 'Weight', type: 'number' },
      { key: 'isConsumabile', label: 'Consumable', type: 'checkbox' },
      { key: 'idClassPermitted', label: 'Class Permitted ID', type: 'number' },
      { key: 'idClassProhibited', label: 'Class Prohibited ID', type: 'number' },
    ],
    'item-effects': [
      { key: 'idItem', label: 'Item ID', type: 'number' },
      { key: 'effectCode', label: 'Effect Code', type: 'text' },
      { key: 'effectValue', label: 'Effect Value', type: 'number' },
    ],
    'character-templates': [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'lifeMax', label: 'Max Life', type: 'number' },
      { key: 'energyMax', label: 'Max Energy', type: 'number' },
      { key: 'sadMax', label: 'Max Sad', type: 'number' },
      { key: 'dexterityStart', label: 'Dexterity Start', type: 'number' },
      { key: 'intelligenceStart', label: 'Intelligence Start', type: 'number' },
      { key: 'constitutionStart', label: 'Constitution Start', type: 'number' },
      { key: 'idClassPermitted', label: 'Class Permitted ID', type: 'number' },
      { key: 'idClassProhibited', label: 'Class Prohibited ID', type: 'number' },
    ],
    classes: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'weightMax', label: 'Max Weight', type: 'number' },
      { key: 'dexterityBase', label: 'Dexterity Base', type: 'number' },
      { key: 'intelligenceBase', label: 'Intelligence Base', type: 'number' },
      { key: 'constitutionBase', label: 'Constitution Base', type: 'number' },
    ],
    'class-bonuses': [
      { key: 'idClass', label: 'Class ID', type: 'number' },
      { key: 'statistic', label: 'Statistic', type: 'select', options: POSSIBLE_STATISTICS_OPTIONS },
      { key: 'value', label: 'Value', type: 'number' },
    ],
    traits: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'costPositive', label: 'Positive Cost', type: 'number' },
      { key: 'costNegative', label: 'Negative Cost', type: 'number' },
      { key: 'idClassPermitted', label: 'Class Permitted ID', type: 'number' },
      { key: 'idClassProhibited', label: 'Class Prohibited ID', type: 'number' },
      { key: 'life', label: 'Life Δ', type: 'number' },
      { key: 'energy', label: 'Energy Δ', type: 'number' },
      { key: 'sad', label: 'Happiness Δ', type: 'number' },
      { key: 'dexterity', label: 'Dexterity Δ', type: 'number' },
      { key: 'intelligence', label: 'Intelligence Δ', type: 'number' },
      { key: 'constitution', label: 'Physique Δ', type: 'number' },
      { key: 'weight', label: 'Carry Δ', type: 'number' },
    ],
    creators: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
//      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idText', label: 'Text ID', type: 'number' },
      { key: 'link', label: 'Link', type: 'text' },
      { key: 'url', label: 'URL', type: 'text' },
      { key: 'urlImage', label: 'Image URL', type: 'text' },
      { key: 'urlEmote', label: 'Emote URL', type: 'text' },
      { key: 'urlInstagram', label: 'Instagram URL', type: 'text' },
    ],
    cards: [
      { key: 'cardType', label: 'Card Type', type: 'select', options: CARD_TYPE_OPTIONS },
      { key: 'idTextTitle', label: 'Title Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'idCreator', label: 'Creator ID', type: 'number' },
      { key: 'linkCopyright', label: 'Copyright Link', type: 'text' },
      { key: 'idTextCopyright', label: 'Copyright Text ID', type: 'number' },
      { key: 'urlImage', label: 'Image URL', type: 'text' },
      { key: 'alternativeImage', label: 'Alternative Image', type: 'text' },
      { key: 'awesomeIcon', label: 'Awesome Icon', type: 'text' },
      { key: 'styleMain', label: 'Style Main', type: 'text' },
      { key: 'styleDetail', label: 'Style Detail', type: 'text' },
      { key: 'styleImageLittle', label: 'Style Image Little', type: 'text' },
      { key: 'styleImageMedium', label: 'Style Image Medium', type: 'text' },
      { key: 'styleImageLarge', label: 'Style Image Large', type: 'text' },
    ],
    texts: [
      { key: 'idText', label: 'Text ID', type: 'number' },
      { key: 'lang', label: 'Language', type: 'text' },
      { key: 'shortText', label: 'Short Text', type: 'text' },
      { key: 'longText', label: 'Long Text', type: 'textarea' },
      { key: 'idTextCopyright', label: 'Copyright Text ID', type: 'number' },
      { key: 'linkCopyright', label: 'Copyright Link', type: 'text' },
      { key: 'idCreator', label: 'Creator ID', type: 'number' },
    ],
    keys: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'value', label: 'Value', type: 'text' },
      { key: 'group', label: 'Group', type: 'text' },
      { key: 'priority', label: 'Priority', type: 'number' },
      { key: 'visibility', label: 'Visibility', type: 'text' },
    ],
    choices: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idEvent', label: 'Event ID', type: 'number' },
      { key: 'idLocation', label: 'Location ID', type: 'number' },
      { key: 'priority', label: 'Priority', type: 'number' },
      { key: 'idTextNarrative', label: 'Narrative Text ID', type: 'number' },
      { key: 'idEventTorun', label: 'Event to Run ID', type: 'number' },
      { key: 'limitSad', label: 'Sad Limit', type: 'number' },
      { key: 'limitDex', label: 'Dex Limit', type: 'number' },
      { key: 'limitInt', label: 'Int Limit', type: 'number' },
      { key: 'limitCos', label: 'Cos Limit', type: 'number' },
      { key: 'otherwiseFlag', label: 'Otherwise Flag', type: 'number' },
      { key: 'isProgress', label: 'Is Progress', type: 'number' },
      { key: 'logicOperator', label: 'Logic Operator', type: 'select', options: LOGIC_OPERATOR_OPTIONS },
    ],
    'choice-conditions': [
      { key: 'idChoices', label: 'Choice ID', type: 'number' },
      { key: 'type', label: 'Type', type: 'select', options: CHOICE_CONDITION_TYPE_OPTIONS },
      { key: 'key', label: 'Key', type: 'text' },
      { key: 'value', label: 'Value', type: 'text' },
      { key: 'operator', label: 'Operator', type: 'select', options: CHOICE_CONDITION_OPERATOR_OPTIONS },
    ],
    'choice-effects': [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idChoices', label: 'Choice ID', type: 'number' },
      { key: 'idScelta', label: 'Scelta ID', type: 'number' },
      { key: 'flagGroup', label: 'Flag Group', type: 'number' },
      { key: 'statistics', label: 'Statistic', type: 'text' },
      { key: 'value', label: 'Value', type: 'number' },
      { key: 'idText', label: 'Text ID', type: 'number' },
      { key: 'key', label: 'Key', type: 'text' },
      { key: 'valueToAdd', label: 'Value to Add', type: 'text' },
      { key: 'valueToRemove', label: 'Value to Remove', type: 'text' },
    ],
    'weather-rules': [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idText', label: 'Text ID', type: 'number' },
      { key: 'probability', label: 'Probability', type: 'number' },
      { key: 'costMoveSafeLocation', label: 'Cost Move Safe', type: 'number' },
      { key: 'costMoveNotSafeLocation', label: 'Cost Move Not Safe', type: 'number' },
      { key: 'conditionKey', label: 'Condition Key', type: 'text' },
      { key: 'conditionKeyValue', label: 'Condition Key Value', type: 'text' },
      { key: 'timeFrom', label: 'Time From', type: 'number' },
      { key: 'timeTo', label: 'Time To', type: 'number' },
      { key: 'active', label: 'Active', type: 'number' },
      { key: 'priority', label: 'Priority', type: 'number' },
      { key: 'deltaEnergy', label: 'Delta Energy', type: 'number' },
      { key: 'idEvent', label: 'Event ID', type: 'number' },
    ],
    'global-random-events': [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'conditionKey', label: 'Condition Key', type: 'text' },
      { key: 'conditionValue', label: 'Condition Value', type: 'text' },
      { key: 'probability', label: 'Probability', type: 'number' },
      { key: 'idText', label: 'Text ID', type: 'number' },
      { key: 'idEvent', label: 'Event ID', type: 'number' },
    ],
    missions: [
      { key: 'idCard', label: 'Card ID', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'conditionKey', label: 'Condition Key', type: 'text' },
      { key: 'conditionValueFrom', label: 'Condition Value From', type: 'number' },
      { key: 'conditionValueTo', label: 'Condition Value To', type: 'number' },
      { key: 'idEventCompleted', label: 'Completed Event ID', type: 'number' },
    ],
    'mission-steps': [
      { key: 'idMission', label: 'Mission ID', type: 'number' },
      { key: 'step', label: 'Step Number', type: 'number' },
      { key: 'idTextName', label: 'Name Text ID', type: 'number' },
      { key: 'idTextDescription', label: 'Desc Text ID', type: 'number' },
      { key: 'conditionKey', label: 'Condition Key', type: 'text' },
      { key: 'conditionValueFrom', label: 'Condition Value From', type: 'number' },
      { key: 'conditionValueTo', label: 'Condition Value To', type: 'number' },
      { key: 'idEventCompleted', label: 'Completed Event ID', type: 'number' },
    ],
  }


export const STORIES_ENTITIES_COLUMNS = {
    difficulties: [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'expCost', label: 'EXP Cost' },
      { key: 'maxWeight', label: 'Max Weight' },
      { key: 'minCharacter', label: 'Min Chars' },
      { key: 'maxCharacter', label: 'Max Chars' },
      { key: 'costHelpComa', label: 'Help COMA' },
      { key: 'costMaxCharacteristics', label: 'Max Char Cost' },
      { key: 'numberMaxFreeAction', label: 'Max Free Actions' },
      { key: 'life', label: 'Life' },
      { key: 'energy', label: 'Energy' },
      { key: 'sad', label: 'Sad' },
      { key: 'dexterity', label: 'Dex' },
      { key: 'intelligence', label: 'Int' },
      { key: 'constitution', label: 'Cos' },
      { key: 'weight', label: 'Wei' },
    ],
    locations: [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'idTextDescription', label: 'Desc', type: 'idTextDescription' },
      { key: 'isSafe', label: 'Safe', type: 'boolean' },
      { key: 'idImage', label: 'Image' },
      { key: 'maxCharacters', label: 'Max Chars' },
    ],
    'location-neighbors': [
      { key: 'flagBack', label: 'Back', render: (ent) => (Number(ent.flagBack) === 1 ? 'YES' : 'NO') },
      { key: 'idLocationFrom', label: 'From' },
      { key: 'idLocationTo', label: 'To' },
      
      { key: 'direction', label: 'Direction' },
    ],
    events: [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'type', label: 'Type' },
      { key: 'idSpecificLocation', label: 'Location' },
      { key: 'costEnery', label: 'Energy Cost' },
      { key: 'coinCost', label: 'Coin Cost' },
      { key: 'flagEndTime', label: 'End Time' },
    ],
    'event-effects': [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'idEvent', label: 'Event ID' },
      { key: 'statistics', label: 'Statistic' },
      { key: 'value', label: 'Value' },
      { key: 'target', label: 'Target' },
    ],
    items: [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'weight', label: 'Weight' },
      { key: 'isConsumabile', label: 'Consumable' },
      { key: 'idClassPermitted', label: 'Class Permitted' },
      { key: 'idClassProhibited', label: 'Class Prohibited' },
    ],
    'item-effects': [
      { key: 'idItem', label: 'Item ID' },
      { key: 'effectCode', label: 'Effect Code' },
      { key: 'effectValue', label: 'Value' },
    ],
    'character-templates': [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'lifeMax', label: 'Max Life' },
      { key: 'energyMax', label: 'Max Energy' },
      { key: 'sadMax', label: 'Max Sad' },
      { key: 'dexterityStart', label: 'Dex Start' },
      { key: 'intelligenceStart', label: 'Int Start' },
      { key: 'constitutionStart', label: 'Con Start' },
      { key: 'idClassPermitted', label: 'Class Permitted' },
      { key: 'idClassProhibited', label: 'Class Prohibited' },
    ],
    classes: [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'weightMax', label: 'Max Weight' },
      { key: 'dexterityBase', label: 'Dex Base' },
      { key: 'intelligenceBase', label: 'Int Base' },
      { key: 'constitutionBase', label: 'Con Base' },
    ],
    'class-bonuses': [
      { key: 'idClass', label: 'Class ID' },
      { key: 'statistic', label: 'Statistic' },
      { key: 'value', label: 'Value' },
    ],
    traits: [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'costPositive', label: 'Cost (+)' },
      { key: 'costNegative', label: 'Cost (-)' },
      { key: 'idClassPermitted', label: 'Class Permitted' },
      { key: 'idClassProhibited', label: 'Class Prohibited' },
      { key: 'life', label: 'Life Δ' },
      { key: 'energy', label: 'Energy Δ' },
      { key: 'sad', label: 'Happiness Δ' },
      { key: 'dexterity', label: 'Dex Δ' },
      { key: 'intelligence', label: 'Int Δ' },
      { key: 'constitution', label: 'Phys Δ' },
      { key: 'weight', label: 'Carry Δ' },
    ],
    creators: [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'link', label: 'Link' },
      { key: 'url', label: 'URL' },
      { key: 'urlEmote', label: 'Emote URL' },
      { key: 'urlInstagram', label: 'Instagram URL' },
    ],
    cards: [
      { key: 'idTextTitle', label: 'Title',  type: 'idTextTitle' },
      { key: 'awesomeIcon', label: 'Icon' },
    ],
    texts: [
      { key: 'idText', label: 'ID Text', type: 'monoId' },
      { key: 'lang', label: 'Lang', type: 'langBadge' },
      { key: 'shortText', label: 'Short Text' },
      { key: 'longText', label: 'Long Text', type: 'longTextIcon' },
      { key: 'idTextCopyright', label: 'Copyright ID' },
      { key: 'idCreator', label: 'Creator ID' },
    ],
    keys: [
      { key: 'name', label: 'Name' },
      { key: 'value', label: 'Value' },
      { key: 'group', label: 'Group' },
      { key: 'priority', label: 'Priority' },
      { key: 'visibility', label: 'Visibility' },
    ],
    choices: [
      { key: 'idEvent', label: 'Event ID' },
      { key: 'idLocation', label: 'Location ID' },
      { key: 'priority', label: 'Priority' },
      { key: 'idTextNarrative', label: 'Narrative Text ID' },
      { key: 'logicOperator', label: 'Logic Op.' },
    ],
    'choice-conditions': [
      { key: 'idChoices', label: 'Choice ID' },
      { key: 'type', label: 'Type' },
      { key: 'key', label: 'Key' },
      { key: 'value', label: 'Value' },
      { key: 'operator', label: 'Operator' },
    ],
    'choice-effects': [
      { key: 'idChoices', label: 'Choice ID' },
      { key: 'statistics', label: 'Statistic' },
      { key: 'value', label: 'Value' },
      { key: 'key', label: 'Key' },
    ],
    'weather-rules': [
      { key: 'idText', label: 'ID Text', type: 'idTextName' },
      { key: 'probability', label: 'Probability' },
      { key: 'conditionKey', label: 'Condition Key' },
      { key: 'timeFrom', label: 'Time From' },
      { key: 'timeTo', label: 'Time To' },
      { key: 'deltaEnergy', label: 'Delta Energy' },
    ],
    'global-random-events': [
      { key: 'conditionKey', label: 'Condition Key' },
      { key: 'conditionValue', label: 'Condition Value' },
      { key: 'probability', label: 'Probability' },
      { key: 'idEvent', label: 'Event ID' },
    ],
    missions: [
      { key: 'idTextName', label: 'Name', type: 'idTextName' },
      { key: 'conditionKey', label: 'Condition Key' },
      { key: 'idEventCompleted', label: 'Completed Event' },
    ],
    'mission-steps': [
      { key: 'idMission', label: 'Mission ID' },
      { key: 'step', label: 'Step' },
      { key: 'conditionKey', label: 'Condition Key' },
      { key: 'idEventCompleted', label: 'Completed Event' },
    ],
  }