version = 0.1

[default.deploy.parameters]
stack_name = "pathsgames-aws-backend"
s3_bucket = "pathsgames-dev"
s3_prefix = "cloudformation-backend"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[dev.deploy.parameters]
stack_name = "pathsgames-dev"
s3_bucket = "pathsgames-dev"
s3_prefix = "cloudformation-backend"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
region = "us-east-2"

[prod.deploy.parameters]
stack_name = "pathsgames-prod"
parameter_overrides = "Environment=prod"
confirm_changeset = false
fail_on_empty_changeset = false
